/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_About (void)
{
  GtkWidget *About;
  const gchar *authors[] = {
    "Author: arcum42(@gmail.com)",
    "Forked from ZeroPad, by:",
    "zerofrog(@gmail.com)",
    "Thanks to:",
    " linuzappz <linuzappz@hotmail.com>",
    "florin sasu <florinsasu@hotmail.com>",
    "and SSSPSXPad, TwinPad authors",
    NULL
  };
  /* TRANSLATORS: Replace this string with your names, one name per line. */
  gchar *translators = _("translator-credits");

  About = gtk_about_dialog_new ();
  gtk_widget_set_name (About, "About");
  gtk_container_set_border_width (GTK_CONTAINER (About), 5);
  gtk_window_set_destroy_with_parent (GTK_WINDOW (About), TRUE);
  gtk_about_dialog_set_version (GTK_ABOUT_DIALOG (About), VERSION);
  gtk_about_dialog_set_name (GTK_ABOUT_DIALOG (About), _("OnePAD"));
  gtk_about_dialog_set_authors (GTK_ABOUT_DIALOG (About), authors);
  gtk_about_dialog_set_translator_credits (GTK_ABOUT_DIALOG (About), translators);

  g_signal_connect ((gpointer) About, "response",
                    G_CALLBACK (OnAbout_Ok),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (About, About, "About");

  return About;
}

GtkWidget*
create_Conf (void)
{
  GtkWidget *Conf;
  GtkWidget *dialog_vbox1;
  GtkWidget *vbox1;
  GtkWidget *frame1;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *PAD1;
  GSList *PAD1_group = NULL;
  GtkWidget *PAD2;
  GtkWidget *PAD3;
  GtkWidget *PAD4;
  GtkWidget *label2;
  GtkWidget *vbox2;
  GtkWidget *label5;
  GtkWidget *joydevicescombo;
  GtkWidget *fixed1;
  GtkWidget *vbox3;
  GtkWidget *hbox3;
  GtkWidget *fixed2;
  GtkWidget *fixed3;
  GtkWidget *Left;
  GtkWidget *Up;
  GtkWidget *Right;
  GtkWidget *Down;
  GtkWidget *L2;
  GtkWidget *L1;
  GtkWidget *Select;
  GtkWidget *Start;
  GtkWidget *L3;
  GtkWidget *R3;
  GtkWidget *Analog;
  GtkWidget *Square;
  GtkWidget *Triangle;
  GtkWidget *Circle;
  GtkWidget *Cross;
  GtkWidget *R2;
  GtkWidget *R1;
  GtkWidget *label3;
  GtkWidget *label6;
  GtkWidget *L_Up;
  GtkWidget *L_Left;
  GtkWidget *Lx;
  GtkWidget *Ly;
  GtkWidget *L_Down;
  GtkWidget *L_Right;
  GtkWidget *checkbutton_reverselx;
  GtkWidget *checkbutton_reversely;
  GtkWidget *R_Up;
  GtkWidget *R_Left;
  GtkWidget *Rx;
  GtkWidget *Ry;
  GtkWidget *R_Right;
  GtkWidget *R_Down;
  GtkWidget *forcefeedback;
  GtkWidget *checkbutton_reverserx;
  GtkWidget *checkbutton_reversery;
  GtkWidget *frame2;
  GtkWidget *alignment2;
  GtkWidget *scrolledwindow2;
  GtkWidget *padtreeview;
  GtkWidget *label7;
  GtkWidget *remove_button;
  GtkWidget *dialog_action_area1;
  GtkWidget *okbutton1;
  GtkWidget *cancelbutton1;

  Conf = gtk_dialog_new ();
  gtk_widget_set_name (Conf, "Conf");
  gtk_window_set_title (GTK_WINDOW (Conf), _("OnePAD Configuration Dialog"));
  gtk_window_set_type_hint (GTK_WINDOW (Conf), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox1 = GTK_DIALOG (Conf)->vbox;
  gtk_widget_set_name (dialog_vbox1, "dialog_vbox1");
  gtk_widget_show (dialog_vbox1);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox1, "vbox1");
  gtk_widget_show (vbox1);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), vbox1, TRUE, TRUE, 0);

  frame1 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame1, "frame1");
  gtk_widget_show (frame1);
  gtk_box_pack_start (GTK_BOX (vbox1), frame1, FALSE, FALSE, 0);

  alignment1 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (alignment1, "alignment1");
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (frame1), alignment1);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment1), 0, 0, 12, 0);

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox1, "hbox1");
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  PAD1 = gtk_radio_button_new_with_mnemonic (NULL, _("PAD1"));
  gtk_widget_set_name (PAD1, "PAD1");
  gtk_widget_show (PAD1);
  gtk_box_pack_start (GTK_BOX (hbox1), PAD1, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (PAD1), PAD1_group);
  PAD1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (PAD1));
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (PAD1), TRUE);

  PAD2 = gtk_radio_button_new_with_mnemonic (NULL, _("PAD2"));
  gtk_widget_set_name (PAD2, "PAD2");
  gtk_widget_show (PAD2);
  gtk_box_pack_start (GTK_BOX (hbox1), PAD2, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (PAD2), PAD1_group);
  PAD1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (PAD2));

  PAD3 = gtk_radio_button_new_with_mnemonic (NULL, _("PAD1 alt."));
  gtk_widget_set_name (PAD3, "PAD3");
  gtk_widget_show (PAD3);
  gtk_box_pack_start (GTK_BOX (hbox1), PAD3, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (PAD3), PAD1_group);
  PAD1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (PAD3));

  PAD4 = gtk_radio_button_new_with_mnemonic (NULL, _("PAD2 alt."));
  gtk_widget_set_name (PAD4, "PAD4");
  gtk_widget_show (PAD4);
  gtk_box_pack_start (GTK_BOX (hbox1), PAD4, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (PAD4), PAD1_group);
  PAD1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (PAD4));

  label2 = gtk_label_new (_("<b>Choose PAD to modify</b>"));
  gtk_widget_set_name (label2, "label2");
  gtk_widget_show (label2);
  gtk_frame_set_label_widget (GTK_FRAME (frame1), label2);
  gtk_label_set_use_markup (GTK_LABEL (label2), TRUE);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox2, "vbox2");
  gtk_widget_show (vbox2);
  gtk_box_pack_start (GTK_BOX (vbox1), vbox2, FALSE, TRUE, 0);

  label5 = gtk_label_new (_("Joystick to use for this PAD"));
  gtk_widget_set_name (label5, "label5");
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (vbox2), label5, FALSE, FALSE, 0);

  joydevicescombo = gtk_combo_box_entry_new_text ();
  gtk_widget_set_name (joydevicescombo, "joydevicescombo");
  gtk_widget_show (joydevicescombo);
  gtk_box_pack_start (GTK_BOX (vbox2), joydevicescombo, FALSE, TRUE, 0);

  fixed1 = gtk_fixed_new ();
  gtk_widget_set_name (fixed1, "fixed1");
  gtk_widget_show (fixed1);
  gtk_box_pack_start (GTK_BOX (vbox1), fixed1, TRUE, TRUE, 0);

  vbox3 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox3, "vbox3");
  gtk_widget_show (vbox3);
  gtk_fixed_put (GTK_FIXED (fixed1), vbox3, 0, 0);
  gtk_widget_set_size_request (vbox3, 0, 0);

  hbox3 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox3, "hbox3");
  gtk_widget_show (hbox3);
  gtk_box_pack_start (GTK_BOX (vbox3), hbox3, FALSE, FALSE, 0);

  fixed2 = gtk_fixed_new ();
  gtk_widget_set_name (fixed2, "fixed2");
  gtk_widget_show (fixed2);
  gtk_box_pack_start (GTK_BOX (hbox3), fixed2, FALSE, FALSE, 0);

  fixed3 = gtk_fixed_new ();
  gtk_widget_set_name (fixed3, "fixed3");
  gtk_widget_show (fixed3);
  gtk_box_pack_start (GTK_BOX (hbox3), fixed3, FALSE, FALSE, 0);

  Left = gtk_button_new_with_mnemonic (_("Left"));
  gtk_widget_set_name (Left, "Left");
  gtk_widget_show (Left);
  gtk_fixed_put (GTK_FIXED (fixed1), Left, 320, 104);
  gtk_widget_set_size_request (Left, 64, 24);

  Up = gtk_button_new_with_mnemonic (_("Up"));
  gtk_widget_set_name (Up, "Up");
  gtk_widget_show (Up);
  gtk_fixed_put (GTK_FIXED (fixed1), Up, 384, 80);
  gtk_widget_set_size_request (Up, 64, 24);

  Right = gtk_button_new_with_mnemonic (_("Right"));
  gtk_widget_set_name (Right, "Right");
  gtk_widget_show (Right);
  gtk_fixed_put (GTK_FIXED (fixed1), Right, 448, 104);
  gtk_widget_set_size_request (Right, 64, 24);

  Down = gtk_button_new_with_mnemonic (_("Down"));
  gtk_widget_set_name (Down, "Down");
  gtk_widget_show (Down);
  gtk_fixed_put (GTK_FIXED (fixed1), Down, 384, 128);
  gtk_widget_set_size_request (Down, 64, 24);

  L2 = gtk_button_new_with_mnemonic (_("L2"));
  gtk_widget_set_name (L2, "L2");
  gtk_widget_show (L2);
  gtk_fixed_put (GTK_FIXED (fixed1), L2, 384, 8);
  gtk_widget_set_size_request (L2, 64, 24);

  L1 = gtk_button_new_with_mnemonic (_("L1"));
  gtk_widget_set_name (L1, "L1");
  gtk_widget_show (L1);
  gtk_fixed_put (GTK_FIXED (fixed1), L1, 384, 32);
  gtk_widget_set_size_request (L1, 64, 24);

  Select = gtk_button_new_with_mnemonic (_("Select"));
  gtk_widget_set_name (Select, "Select");
  gtk_widget_show (Select);
  gtk_fixed_put (GTK_FIXED (fixed1), Select, 520, 48);
  gtk_widget_set_size_request (Select, 64, 24);

  Start = gtk_button_new_with_mnemonic (_("Start"));
  gtk_widget_set_name (Start, "Start");
  gtk_widget_show (Start);
  gtk_fixed_put (GTK_FIXED (fixed1), Start, 592, 48);
  gtk_widget_set_size_request (Start, 64, 24);

  L3 = gtk_button_new_with_mnemonic (_("L3"));
  gtk_widget_set_name (L3, "L3");
  gtk_widget_show (L3);
  gtk_fixed_put (GTK_FIXED (fixed1), L3, 520, 8);
  gtk_widget_set_size_request (L3, 64, 24);

  R3 = gtk_button_new_with_mnemonic (_("R3"));
  gtk_widget_set_name (R3, "R3");
  gtk_widget_show (R3);
  gtk_fixed_put (GTK_FIXED (fixed1), R3, 592, 8);
  gtk_widget_set_size_request (R3, 64, 24);

  Analog = gtk_button_new_with_mnemonic (_("Analog"));
  gtk_widget_set_name (Analog, "Analog");
  gtk_widget_show (Analog);
  gtk_fixed_put (GTK_FIXED (fixed1), Analog, 552, 104);
  gtk_widget_set_size_request (Analog, 64, 24);

  Square = gtk_button_new_with_mnemonic (_("Square"));
  gtk_widget_set_name (Square, "Square");
  gtk_widget_show (Square);
  gtk_fixed_put (GTK_FIXED (fixed1), Square, 648, 104);
  gtk_widget_set_size_request (Square, 64, 24);

  Triangle = gtk_button_new_with_mnemonic (_("Triangle"));
  gtk_widget_set_name (Triangle, "Triangle");
  gtk_widget_show (Triangle);
  gtk_fixed_put (GTK_FIXED (fixed1), Triangle, 712, 80);
  gtk_widget_set_size_request (Triangle, 64, 24);

  Circle = gtk_button_new_with_mnemonic (_("Circle"));
  gtk_widget_set_name (Circle, "Circle");
  gtk_widget_show (Circle);
  gtk_fixed_put (GTK_FIXED (fixed1), Circle, 776, 104);
  gtk_widget_set_size_request (Circle, 64, 24);

  Cross = gtk_button_new_with_mnemonic (_("Cross"));
  gtk_widget_set_name (Cross, "Cross");
  gtk_widget_show (Cross);
  gtk_fixed_put (GTK_FIXED (fixed1), Cross, 712, 128);
  gtk_widget_set_size_request (Cross, 64, 24);

  R2 = gtk_button_new_with_mnemonic (_("R2"));
  gtk_widget_set_name (R2, "R2");
  gtk_widget_show (R2);
  gtk_fixed_put (GTK_FIXED (fixed1), R2, 712, 8);
  gtk_widget_set_size_request (R2, 64, 24);

  R1 = gtk_button_new_with_mnemonic (_("R1"));
  gtk_widget_set_name (R1, "R1");
  gtk_widget_show (R1);
  gtk_fixed_put (GTK_FIXED (fixed1), R1, 712, 32);
  gtk_widget_set_size_request (R1, 64, 24);

  label3 = gtk_label_new (_("Analog Controls (move mouse or analog joystick to select)"));
  gtk_widget_set_name (label3, "label3");
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed1), label3, 384, 168);
  gtk_widget_set_size_request (label3, 400, 24);
  gtk_label_set_line_wrap (GTK_LABEL (label3), TRUE);
  gtk_label_set_single_line_mode (GTK_LABEL (label3), TRUE);

  label6 = gtk_label_new (_("(Note: The analog key controls and joystick controls do not work well together currently, and should not be mixed. )"));
  gtk_widget_set_name (label6, "label6");
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed1), label6, 352, 192);
  gtk_widget_set_size_request (label6, 448, 40);
  gtk_label_set_justify (GTK_LABEL (label6), GTK_JUSTIFY_CENTER);
  gtk_label_set_line_wrap (GTK_LABEL (label6), TRUE);

  L_Up = gtk_button_new_with_mnemonic (_("Up"));
  gtk_widget_set_name (L_Up, "L_Up");
  gtk_widget_show (L_Up);
  gtk_fixed_put (GTK_FIXED (fixed1), L_Up, 384, 240);
  gtk_widget_set_size_request (L_Up, 64, 24);

  L_Left = gtk_button_new_with_mnemonic (_("Left"));
  gtk_widget_set_name (L_Left, "L_Left");
  gtk_widget_show (L_Left);
  gtk_fixed_put (GTK_FIXED (fixed1), L_Left, 320, 272);
  gtk_widget_set_size_request (L_Left, 64, 24);

  Lx = gtk_button_new_with_mnemonic (_("Lx"));
  gtk_widget_set_name (Lx, "Lx");
  gtk_widget_show (Lx);
  gtk_fixed_put (GTK_FIXED (fixed1), Lx, 384, 264);
  gtk_widget_set_size_request (Lx, 64, 24);

  Ly = gtk_button_new_with_mnemonic (_("Ly"));
  gtk_widget_set_name (Ly, "Ly");
  gtk_widget_show (Ly);
  gtk_fixed_put (GTK_FIXED (fixed1), Ly, 384, 288);
  gtk_widget_set_size_request (Ly, 64, 24);

  L_Down = gtk_button_new_with_mnemonic (_("Down"));
  gtk_widget_set_name (L_Down, "L_Down");
  gtk_widget_show (L_Down);
  gtk_fixed_put (GTK_FIXED (fixed1), L_Down, 384, 312);
  gtk_widget_set_size_request (L_Down, 64, 24);

  L_Right = gtk_button_new_with_mnemonic (_("Right"));
  gtk_widget_set_name (L_Right, "L_Right");
  gtk_widget_show (L_Right);
  gtk_fixed_put (GTK_FIXED (fixed1), L_Right, 448, 272);
  gtk_widget_set_size_request (L_Right, 64, 24);

  checkbutton_reverselx = gtk_check_button_new_with_mnemonic (_("Reverse LX"));
  gtk_widget_set_name (checkbutton_reverselx, "checkbutton_reverselx");
  gtk_widget_show (checkbutton_reverselx);
  gtk_fixed_put (GTK_FIXED (fixed1), checkbutton_reverselx, 360, 344);
  gtk_widget_set_size_request (checkbutton_reverselx, 111, 22);

  checkbutton_reversely = gtk_check_button_new_with_mnemonic (_("Reverse LY"));
  gtk_widget_set_name (checkbutton_reversely, "checkbutton_reversely");
  gtk_widget_show (checkbutton_reversely);
  gtk_fixed_put (GTK_FIXED (fixed1), checkbutton_reversely, 360, 368);
  gtk_widget_set_size_request (checkbutton_reversely, 111, 22);

  R_Up = gtk_button_new_with_mnemonic (_("Up"));
  gtk_widget_set_name (R_Up, "R_Up");
  gtk_widget_show (R_Up);
  gtk_fixed_put (GTK_FIXED (fixed1), R_Up, 712, 240);
  gtk_widget_set_size_request (R_Up, 64, 24);

  R_Left = gtk_button_new_with_mnemonic (_("Left"));
  gtk_widget_set_name (R_Left, "R_Left");
  gtk_widget_show (R_Left);
  gtk_fixed_put (GTK_FIXED (fixed1), R_Left, 648, 272);
  gtk_widget_set_size_request (R_Left, 64, 24);

  Rx = gtk_button_new_with_mnemonic (_("Rx"));
  gtk_widget_set_name (Rx, "Rx");
  gtk_widget_show (Rx);
  gtk_fixed_put (GTK_FIXED (fixed1), Rx, 712, 264);
  gtk_widget_set_size_request (Rx, 64, 24);

  Ry = gtk_button_new_with_mnemonic (_("Ry"));
  gtk_widget_set_name (Ry, "Ry");
  gtk_widget_show (Ry);
  gtk_fixed_put (GTK_FIXED (fixed1), Ry, 712, 288);
  gtk_widget_set_size_request (Ry, 64, 24);

  R_Right = gtk_button_new_with_mnemonic (_("Right"));
  gtk_widget_set_name (R_Right, "R_Right");
  gtk_widget_show (R_Right);
  gtk_fixed_put (GTK_FIXED (fixed1), R_Right, 776, 272);
  gtk_widget_set_size_request (R_Right, 64, 24);

  R_Down = gtk_button_new_with_mnemonic (_("Down"));
  gtk_widget_set_name (R_Down, "R_Down");
  gtk_widget_show (R_Down);
  gtk_fixed_put (GTK_FIXED (fixed1), R_Down, 712, 312);
  gtk_widget_set_size_request (R_Down, 64, 24);

  forcefeedback = gtk_check_button_new_with_mnemonic (_("Enable Force\nFeedback"));
  gtk_widget_set_name (forcefeedback, "forcefeedback");
  gtk_widget_show (forcefeedback);
  gtk_fixed_put (GTK_FIXED (fixed1), forcefeedback, 528, 344);
  gtk_widget_set_size_request (forcefeedback, 112, 48);

  checkbutton_reverserx = gtk_check_button_new_with_mnemonic (_("Reverse RX"));
  gtk_widget_set_name (checkbutton_reverserx, "checkbutton_reverserx");
  gtk_widget_show (checkbutton_reverserx);
  gtk_fixed_put (GTK_FIXED (fixed1), checkbutton_reverserx, 688, 344);
  gtk_widget_set_size_request (checkbutton_reverserx, 111, 22);

  checkbutton_reversery = gtk_check_button_new_with_mnemonic (_("Reverse RY"));
  gtk_widget_set_name (checkbutton_reversery, "checkbutton_reversery");
  gtk_widget_show (checkbutton_reversery);
  gtk_fixed_put (GTK_FIXED (fixed1), checkbutton_reversery, 688, 368);
  gtk_widget_set_size_request (checkbutton_reversery, 111, 22);

  frame2 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame2, "frame2");
  gtk_widget_show (frame2);
  gtk_fixed_put (GTK_FIXED (fixed1), frame2, 0, 8);
  gtk_widget_set_size_request (frame2, 312, 336);

  alignment2 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (alignment2, "alignment2");
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (frame2), alignment2);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment2), 0, 0, 12, 0);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scrolledwindow2, "scrolledwindow2");
  gtk_widget_show (scrolledwindow2);
  gtk_container_add (GTK_CONTAINER (alignment2), scrolledwindow2);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow2), GTK_SHADOW_IN);

  padtreeview = gtk_tree_view_new ();
  gtk_widget_set_name (padtreeview, "padtreeview");
  gtk_widget_show (padtreeview);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), padtreeview);
  gtk_widget_set_extension_events (padtreeview, GDK_EXTENSION_EVENTS_ALL);
  gtk_tree_view_set_rules_hint (GTK_TREE_VIEW (padtreeview), TRUE);
  gtk_tree_view_set_enable_search (GTK_TREE_VIEW (padtreeview), FALSE);
  gtk_tree_view_set_hover_expand (GTK_TREE_VIEW (padtreeview), TRUE);

  label7 = gtk_label_new (_("Key Settings"));
  gtk_widget_set_name (label7, "label7");
  gtk_widget_show (label7);
  gtk_frame_set_label_widget (GTK_FRAME (frame2), label7);

  remove_button = gtk_button_new_with_mnemonic (_("Remove"));
  gtk_widget_set_name (remove_button, "remove_button");
  gtk_widget_show (remove_button);
  gtk_fixed_put (GTK_FIXED (fixed1), remove_button, 248, 352);
  gtk_widget_set_size_request (remove_button, 0, 0);

  dialog_action_area1 = GTK_DIALOG (Conf)->action_area;
  gtk_widget_set_name (dialog_action_area1, "dialog_action_area1");
  gtk_widget_show (dialog_action_area1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area1), GTK_BUTTONBOX_END);

  okbutton1 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_set_name (okbutton1, "okbutton1");
  gtk_widget_show (okbutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (Conf), okbutton1, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (okbutton1, GTK_CAN_DEFAULT);

  cancelbutton1 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_set_name (cancelbutton1, "cancelbutton1");
  gtk_widget_show (cancelbutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (Conf), cancelbutton1, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (cancelbutton1, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) PAD1, "clicked",
                    G_CALLBACK (OnConf_Pad1),
                    NULL);
  g_signal_connect ((gpointer) PAD2, "clicked",
                    G_CALLBACK (OnConf_Pad2),
                    NULL);
  g_signal_connect ((gpointer) PAD3, "clicked",
                    G_CALLBACK (OnConf_Pad3),
                    NULL);
  g_signal_connect ((gpointer) PAD4, "clicked",
                    G_CALLBACK (OnConf_Pad4),
                    NULL);
  g_signal_connect ((gpointer) joydevicescombo, "changed",
                    G_CALLBACK (on_joydevicescombo_changed),
                    NULL);
  g_signal_connect ((gpointer) Left, "clicked",
                    G_CALLBACK (OnConf_Key),
                    NULL);
  g_signal_connect ((gpointer) Up, "clicked",
                    G_CALLBACK (OnConf_Key),
                    NULL);
  g_signal_connect ((gpointer) Right, "clicked",
                    G_CALLBACK (OnConf_Key),
                    NULL);
  g_signal_connect ((gpointer) Down, "clicked",
                    G_CALLBACK (OnConf_Key),
                    NULL);
  g_signal_connect ((gpointer) L2, "clicked",
                    G_CALLBACK (OnConf_Key),
                    NULL);
  g_signal_connect ((gpointer) L1, "clicked",
                    G_CALLBACK (OnConf_Key),
                    NULL);
  g_signal_connect ((gpointer) Select, "clicked",
                    G_CALLBACK (OnConf_Key),
                    NULL);
  g_signal_connect ((gpointer) Start, "clicked",
                    G_CALLBACK (OnConf_Key),
                    NULL);
  g_signal_connect ((gpointer) L3, "clicked",
                    G_CALLBACK (OnConf_Key),
                    NULL);
  g_signal_connect ((gpointer) R3, "clicked",
                    G_CALLBACK (OnConf_Key),
                    NULL);
  g_signal_connect ((gpointer) Analog, "clicked",
                    G_CALLBACK (OnConf_Key),
                    NULL);
  g_signal_connect ((gpointer) Square, "clicked",
                    G_CALLBACK (OnConf_Key),
                    NULL);
  g_signal_connect ((gpointer) Triangle, "clicked",
                    G_CALLBACK (OnConf_Key),
                    NULL);
  g_signal_connect ((gpointer) Circle, "clicked",
                    G_CALLBACK (OnConf_Key),
                    NULL);
  g_signal_connect ((gpointer) Cross, "clicked",
                    G_CALLBACK (OnConf_Key),
                    NULL);
  g_signal_connect ((gpointer) R2, "clicked",
                    G_CALLBACK (OnConf_Key),
                    NULL);
  g_signal_connect ((gpointer) R1, "clicked",
                    G_CALLBACK (OnConf_Key),
                    NULL);
  g_signal_connect ((gpointer) L_Up, "clicked",
                    G_CALLBACK (OnConf_Key),
                    NULL);
  g_signal_connect ((gpointer) L_Left, "clicked",
                    G_CALLBACK (OnConf_Key),
                    NULL);
  g_signal_connect ((gpointer) Lx, "clicked",
                    G_CALLBACK (OnConf_Key),
                    NULL);
  g_signal_connect ((gpointer) Ly, "clicked",
                    G_CALLBACK (OnConf_Key),
                    NULL);
  g_signal_connect ((gpointer) L_Down, "clicked",
                    G_CALLBACK (OnConf_Key),
                    NULL);
  g_signal_connect ((gpointer) L_Right, "clicked",
                    G_CALLBACK (OnConf_Key),
                    NULL);
  g_signal_connect ((gpointer) checkbutton_reverselx, "toggled",
                    G_CALLBACK (on_checkbutton_reverselx_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton_reversely, "toggled",
                    G_CALLBACK (on_checkbutton_reversely_toggled),
                    NULL);
  g_signal_connect ((gpointer) R_Up, "clicked",
                    G_CALLBACK (OnConf_Key),
                    NULL);
  g_signal_connect ((gpointer) R_Left, "clicked",
                    G_CALLBACK (OnConf_Key),
                    NULL);
  g_signal_connect ((gpointer) Rx, "clicked",
                    G_CALLBACK (OnConf_Key),
                    NULL);
  g_signal_connect ((gpointer) Ry, "clicked",
                    G_CALLBACK (OnConf_Key),
                    NULL);
  g_signal_connect ((gpointer) R_Right, "clicked",
                    G_CALLBACK (OnConf_Key),
                    NULL);
  g_signal_connect ((gpointer) R_Down, "clicked",
                    G_CALLBACK (OnConf_Key),
                    NULL);
  g_signal_connect ((gpointer) forcefeedback, "toggled",
                    G_CALLBACK (on_forcefeedback_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton_reverserx, "toggled",
                    G_CALLBACK (on_checkbutton_reverserx_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton_reversery, "toggled",
                    G_CALLBACK (on_checkbutton_reversery_toggled),
                    NULL);
  g_signal_connect ((gpointer) remove_button, "clicked",
                    G_CALLBACK (on_Remove),
                    NULL);
  g_signal_connect ((gpointer) okbutton1, "clicked",
                    G_CALLBACK (OnConf_Ok),
                    NULL);
  g_signal_connect ((gpointer) cancelbutton1, "clicked",
                    G_CALLBACK (OnConf_Cancel),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Conf, Conf, "Conf");
  GLADE_HOOKUP_OBJECT_NO_REF (Conf, dialog_vbox1, "dialog_vbox1");
  GLADE_HOOKUP_OBJECT (Conf, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (Conf, frame1, "frame1");
  GLADE_HOOKUP_OBJECT (Conf, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (Conf, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (Conf, PAD1, "PAD1");
  GLADE_HOOKUP_OBJECT (Conf, PAD2, "PAD2");
  GLADE_HOOKUP_OBJECT (Conf, PAD3, "PAD3");
  GLADE_HOOKUP_OBJECT (Conf, PAD4, "PAD4");
  GLADE_HOOKUP_OBJECT (Conf, label2, "label2");
  GLADE_HOOKUP_OBJECT (Conf, vbox2, "vbox2");
  GLADE_HOOKUP_OBJECT (Conf, label5, "label5");
  GLADE_HOOKUP_OBJECT (Conf, joydevicescombo, "joydevicescombo");
  GLADE_HOOKUP_OBJECT (Conf, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (Conf, vbox3, "vbox3");
  GLADE_HOOKUP_OBJECT (Conf, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (Conf, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (Conf, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (Conf, Left, "Left");
  GLADE_HOOKUP_OBJECT (Conf, Up, "Up");
  GLADE_HOOKUP_OBJECT (Conf, Right, "Right");
  GLADE_HOOKUP_OBJECT (Conf, Down, "Down");
  GLADE_HOOKUP_OBJECT (Conf, L2, "L2");
  GLADE_HOOKUP_OBJECT (Conf, L1, "L1");
  GLADE_HOOKUP_OBJECT (Conf, Select, "Select");
  GLADE_HOOKUP_OBJECT (Conf, Start, "Start");
  GLADE_HOOKUP_OBJECT (Conf, L3, "L3");
  GLADE_HOOKUP_OBJECT (Conf, R3, "R3");
  GLADE_HOOKUP_OBJECT (Conf, Analog, "Analog");
  GLADE_HOOKUP_OBJECT (Conf, Square, "Square");
  GLADE_HOOKUP_OBJECT (Conf, Triangle, "Triangle");
  GLADE_HOOKUP_OBJECT (Conf, Circle, "Circle");
  GLADE_HOOKUP_OBJECT (Conf, Cross, "Cross");
  GLADE_HOOKUP_OBJECT (Conf, R2, "R2");
  GLADE_HOOKUP_OBJECT (Conf, R1, "R1");
  GLADE_HOOKUP_OBJECT (Conf, label3, "label3");
  GLADE_HOOKUP_OBJECT (Conf, label6, "label6");
  GLADE_HOOKUP_OBJECT (Conf, L_Up, "L_Up");
  GLADE_HOOKUP_OBJECT (Conf, L_Left, "L_Left");
  GLADE_HOOKUP_OBJECT (Conf, Lx, "Lx");
  GLADE_HOOKUP_OBJECT (Conf, Ly, "Ly");
  GLADE_HOOKUP_OBJECT (Conf, L_Down, "L_Down");
  GLADE_HOOKUP_OBJECT (Conf, L_Right, "L_Right");
  GLADE_HOOKUP_OBJECT (Conf, checkbutton_reverselx, "checkbutton_reverselx");
  GLADE_HOOKUP_OBJECT (Conf, checkbutton_reversely, "checkbutton_reversely");
  GLADE_HOOKUP_OBJECT (Conf, R_Up, "R_Up");
  GLADE_HOOKUP_OBJECT (Conf, R_Left, "R_Left");
  GLADE_HOOKUP_OBJECT (Conf, Rx, "Rx");
  GLADE_HOOKUP_OBJECT (Conf, Ry, "Ry");
  GLADE_HOOKUP_OBJECT (Conf, R_Right, "R_Right");
  GLADE_HOOKUP_OBJECT (Conf, R_Down, "R_Down");
  GLADE_HOOKUP_OBJECT (Conf, forcefeedback, "forcefeedback");
  GLADE_HOOKUP_OBJECT (Conf, checkbutton_reverserx, "checkbutton_reverserx");
  GLADE_HOOKUP_OBJECT (Conf, checkbutton_reversery, "checkbutton_reversery");
  GLADE_HOOKUP_OBJECT (Conf, frame2, "frame2");
  GLADE_HOOKUP_OBJECT (Conf, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (Conf, scrolledwindow2, "scrolledwindow2");
  GLADE_HOOKUP_OBJECT (Conf, padtreeview, "padtreeview");
  GLADE_HOOKUP_OBJECT (Conf, label7, "label7");
  GLADE_HOOKUP_OBJECT (Conf, remove_button, "remove_button");
  GLADE_HOOKUP_OBJECT_NO_REF (Conf, dialog_action_area1, "dialog_action_area1");
  GLADE_HOOKUP_OBJECT (Conf, okbutton1, "okbutton1");
  GLADE_HOOKUP_OBJECT (Conf, cancelbutton1, "cancelbutton1");

  return Conf;
}

