#pragma once

class CPUThread;

enum DbgCommand
{
	DID_FIRST_COMMAND = 0x500,

	DID_START_EMU,
	DID_STARTED_EMU,
	DID_STOP_EMU,
	DID_STOPPED_EMU,
	DID_PAUSE_EMU,
	DID_PAUSED_EMU,
	DID_RESUME_EMU,
	DID_RESUMED_EMU,
	DID_READY_EMU,
	DID_CREATE_THREAD,
	DID_CREATED_THREAD,
	DID_REMOVE_THREAD,
	DID_REMOVED_THREAD,
	DID_RENAME_THREAD,
	DID_RENAMED_THREAD,
	DID_START_THREAD,
	DID_STARTED_THREAD,
	DID_STOP_THREAD,
	DID_STOPED_THREAD,
	DID_PAUSE_THREAD,
	DID_PAUSED_THREAD,
	DID_RESUME_THREAD,
	DID_RESUMED_THREAD,
	DID_EXEC_THREAD,
	DID_REGISTRED_CALLBACK,
	DID_UNREGISTRED_CALLBACK,

	DID_LAST_COMMAND,
};

typedef void(*SendDbgCommandCb)(DbgCommand id, CPUThread* t);

void SetSendDbgCommandCallback(SendDbgCommandCb value);

void SendDbgCommand(DbgCommand id, CPUThread* thr = nullptr);