#include "stdafx.h"
#include "rpcn_countries.h"

namespace countries
{
	const std::array<country_code, 72> g_countries =
		{
			country_code{"Japan", "jp"},
			country_code{"United States", "us"},
			country_code{"Argentina", "ar"},
			country_code{"Australia", "au"},
			country_code{"Austria", "at"},
			country_code{"Bahrain", "bh"},
			country_code{"Belgium", "be"},
			country_code{"Bolivia", "bo"},
			country_code{"Brazil", "br"},
			country_code{"Bulgaria", "bg"},
			country_code{"Canada", "ca"},
			country_code{"Chile", "cl"},
			country_code{"China", "cn"},
			country_code{"Colombia", "co"},
			country_code{"Costa Rica", "cr"},
			country_code{"Croatia", "hr"},
			country_code{"Cyprus", "cy"},
			country_code{"Czech Republic", "cz"},
			country_code{"Denmark", "dk"},
			country_code{"Ecuador", "ec"},
			country_code{"El Salvador", "sv"},
			country_code{"Finland", "fi"},
			country_code{"France", "fr"},
			country_code{"Germany", "de"},
			country_code{"Greece", "gr"},
			country_code{"Guatemala", "gt"},
			country_code{"Honduras", "hn"},
			country_code{"Hong Kong", "hk"},
			country_code{"Hungary", "hu"},
			country_code{"Iceland", "is"},
			country_code{"India", "in"},
			country_code{"Indonesia", "id"},
			country_code{"Ireland", "ie"},
			country_code{"Israel", "il"},
			country_code{"Italy", "it"},
			country_code{"Korea", "kr"},
			country_code{"Kuwait", "kw"},
			country_code{"Lebanon", "lb"},
			country_code{"Luxembourg", "lu"},
			country_code{"Malaysia", "my"},
			country_code{"Malta", "mt"},
			country_code{"Mexico", "mx"},
			country_code{"Netherlands", "nl"},
			country_code{"New Zealand", "nz"},
			country_code{"Nicaragua", "ni"},
			country_code{"Norway", "no"},
			country_code{"Oman", "om"},
			country_code{"Panama", "pa"},
			country_code{"Paraguay", "py"},
			country_code{"Peru", "pe"},
			country_code{"Philippines", "ph"},
			country_code{"Poland", "pl"},
			country_code{"Portugal", "pt"},
			country_code{"Qatar", "qa"},
			country_code{"Romania", "ro"},
			country_code{"Russia", "ru"},
			country_code{"Saudi Arabia", "sa"},
			country_code{"Serbia", "rs"},
			country_code{"Singapore", "sg"},
			country_code{"Slovakia", "sk"},
			country_code{"South Africa", "za"},
			country_code{"Spain", "es"},
			country_code{"Sweden", "se"},
			country_code{"Switzerland", "ch"},
			country_code{"Taiwan", "tw"},
			country_code{"Thailand", "th"},
			country_code{"Turkey", "tr"},
			country_code{"Ukraine", "ua"},
			country_code{"United Arab Emirates", "ae"},
			country_code{"United Kingdom", "gb"},
			country_code{"Uruguay", "uy"},
			country_code{"Vietnam", "vn"}
		};
} // namespace countries

