/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_About (void)
{
  GtkWidget *About;
  /* TRANSLATORS: Replace this string with your names, one name per line. */
  gchar *translators = _("translator-credits");

  About = gtk_about_dialog_new ();
  gtk_container_set_border_width (GTK_CONTAINER (About), 5);
  gtk_about_dialog_set_version (GTK_ABOUT_DIALOG (About), VERSION);
  gtk_about_dialog_set_name (GTK_ABOUT_DIALOG (About), _("ZeroSPU2"));
  gtk_about_dialog_set_translator_credits (GTK_ABOUT_DIALOG (About), translators);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (About, About, "About");

  return About;
}

GtkWidget*
create_Config (void)
{
  GtkWidget *Config;
  GtkWidget *dialog_vbox1;
  GtkWidget *vbox1;
  GtkWidget *timescalingbutton;
  GtkWidget *realtimebutton;
  GtkWidget *recordingbutton;
  GtkWidget *mutebutton;
  GtkWidget *loggingbutton;
  GtkWidget *dialog_action_area1;
  GtkWidget *Conf_Ok;
  GtkWidget *Conf_Cancel;

  Config = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (Config), _("ZeroSPU2 Config"));
  gtk_window_set_type_hint (GTK_WINDOW (Config), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox1 = GTK_DIALOG (Config)->vbox;
  gtk_widget_show (dialog_vbox1);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), vbox1, TRUE, TRUE, 0);

  timescalingbutton = gtk_check_button_new_with_mnemonic (_("Time Scaling (recommended) \nSlows down or speeds up sound with respect to game's real speed. \nEnabling this produces higher quality sound with less cracking, but can reduce speed."));
  gtk_widget_show (timescalingbutton);
  gtk_box_pack_start (GTK_BOX (vbox1), timescalingbutton, FALSE, FALSE, 0);

  realtimebutton = gtk_check_button_new_with_mnemonic (_("Real Time mode \nTries to reduce delays in music as much possible. \nUse when game is already fast and need sound tightly synchronized.\n(like in DDR, Guitar Hero, Guitaroo Man)"));
  gtk_widget_show (realtimebutton);
  gtk_box_pack_start (GTK_BOX (vbox1), realtimebutton, FALSE, FALSE, 0);

  recordingbutton = gtk_check_button_new_with_mnemonic (_("Recording - Saves the raw 16bit stereo wav data to zerospu2.wav. Timed to ps2 time."));
  gtk_widget_show (recordingbutton);
  gtk_box_pack_start (GTK_BOX (vbox1), recordingbutton, FALSE, FALSE, 0);

  mutebutton = gtk_check_button_new_with_mnemonic (_("Mute - ZeroSPU2 will not output any sound (fast)."));
  gtk_widget_show (mutebutton);
  gtk_box_pack_start (GTK_BOX (vbox1), mutebutton, FALSE, FALSE, 0);

  loggingbutton = gtk_check_button_new_with_mnemonic (_("Enable logging(for development use only)"));
  gtk_widget_show (loggingbutton);
  gtk_box_pack_start (GTK_BOX (vbox1), loggingbutton, FALSE, FALSE, 0);

  dialog_action_area1 = GTK_DIALOG (Config)->action_area;
  gtk_widget_show (dialog_action_area1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area1), GTK_BUTTONBOX_END);

  Conf_Ok = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (Conf_Ok);
  gtk_dialog_add_action_widget (GTK_DIALOG (Config), Conf_Ok, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (Conf_Ok, GTK_CAN_DEFAULT);

  Conf_Cancel = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (Conf_Cancel);
  gtk_dialog_add_action_widget (GTK_DIALOG (Config), Conf_Cancel, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (Conf_Cancel, GTK_CAN_DEFAULT);

  g_signal_connect ((gpointer) Conf_Ok, "clicked",
                    G_CALLBACK (on_Conf_Ok),
                    NULL);
  g_signal_connect ((gpointer) Conf_Cancel, "clicked",
                    G_CALLBACK (on_Conf_Cancel),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Config, Config, "Config");
  GLADE_HOOKUP_OBJECT_NO_REF (Config, dialog_vbox1, "dialog_vbox1");
  GLADE_HOOKUP_OBJECT (Config, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (Config, timescalingbutton, "timescalingbutton");
  GLADE_HOOKUP_OBJECT (Config, realtimebutton, "realtimebutton");
  GLADE_HOOKUP_OBJECT (Config, recordingbutton, "recordingbutton");
  GLADE_HOOKUP_OBJECT (Config, mutebutton, "mutebutton");
  GLADE_HOOKUP_OBJECT (Config, loggingbutton, "loggingbutton");
  GLADE_HOOKUP_OBJECT_NO_REF (Config, dialog_action_area1, "dialog_action_area1");
  GLADE_HOOKUP_OBJECT (Config, Conf_Ok, "Conf_Ok");
  GLADE_HOOKUP_OBJECT (Config, Conf_Cancel, "Conf_Cancel");

  return Config;
}

