/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

GtkWidget*
create_Config (void)
{
  GtkWidget *Config;
  GtkWidget *vbox4;
  GtkWidget *hbox5;
  GtkWidget *vbox1;
  GtkWidget *frame2;
  GtkWidget *vbox8;
  GtkWidget *hbox1;
  GtkWidget *label1;
  GtkWidget *GtkCombo_FRes;
  GtkWidget *combo_entry1;
  GtkWidget *hbox6;
  GtkWidget *label6;
  GtkWidget *GtkCombo_WRes;
  GtkWidget *entry1;
  GtkWidget *frame1;
  GtkWidget *table1;
  GtkWidget *GtkCheckButton_Fps;
  GtkWidget *GtkCheckButton_Frameskip;
  GtkWidget *GtkCheckButton_Fullscreen;
  GtkWidget *GtkCheckButton_Stretch;
  GtkWidget *label7;
  GtkWidget *GtkCombo_Filters;
  GtkWidget *combo_entry4;
  GtkWidget *vbox6;
  GtkWidget *frame4;
  GtkWidget *vbox5;
  GtkWidget *GtkCheckButton_Cache;
  GtkWidget *hbox2;
  GtkWidget *label5;
  GtkWidget *GtkCombo_CacheSize;
  GtkWidget *combo_entry2;
  GtkWidget *GtkFrame_Rec;
  GtkWidget *vbox7;
  GtkWidget *GtkCheckButton_Record;
  GtkWidget *GtkCombo_Codec;
  GtkWidget *combo_entry3;
  GtkWidget *hbuttonbox1;
  GtkWidget *button1;
  GtkWidget *button2;
  GtkWidget *GtkButton_Logging;

  Config = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (Config), "Config", Config);
  gtk_container_set_border_width (GTK_CONTAINER (Config), 5);
  gtk_window_set_title (GTK_WINDOW (Config), "GSconfig");
  gtk_window_set_position (GTK_WINDOW (Config), GTK_WIN_POS_CENTER);
  gtk_window_set_policy (GTK_WINDOW (Config), FALSE, FALSE, FALSE);

  vbox4 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox4);
  gtk_object_set_data_full (GTK_OBJECT (Config), "vbox4", vbox4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox4);
  gtk_container_add (GTK_CONTAINER (Config), vbox4);

  hbox5 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox5);
  gtk_object_set_data_full (GTK_OBJECT (Config), "hbox5", hbox5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox5);
  gtk_box_pack_start (GTK_BOX (vbox4), hbox5, TRUE, TRUE, 0);

  vbox1 = gtk_vbox_new (FALSE, 5);
  gtk_widget_ref (vbox1);
  gtk_object_set_data_full (GTK_OBJECT (Config), "vbox1", vbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox1);
  gtk_box_pack_start (GTK_BOX (hbox5), vbox1, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (vbox1), 5);

  frame2 = gtk_frame_new ("Display Setup");
  gtk_widget_ref (frame2);
  gtk_object_set_data_full (GTK_OBJECT (Config), "frame2", frame2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame2);
  gtk_box_pack_start (GTK_BOX (vbox1), frame2, TRUE, TRUE, 0);

  vbox8 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox8);
  gtk_object_set_data_full (GTK_OBJECT (Config), "vbox8", vbox8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox8);
  gtk_container_add (GTK_CONTAINER (frame2), vbox8);

  hbox1 = gtk_hbox_new (FALSE, 5);
  gtk_widget_ref (hbox1);
  gtk_object_set_data_full (GTK_OBJECT (Config), "hbox1", hbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox8), hbox1, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox1), 5);

  label1 = gtk_label_new ("Fullscreen Resolution");
  gtk_widget_ref (label1);
  gtk_object_set_data_full (GTK_OBJECT (Config), "label1", label1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (hbox1), label1, FALSE, FALSE, 0);

  GtkCombo_FRes = gtk_combo_new ();
  gtk_widget_ref (GtkCombo_FRes);
  gtk_object_set_data_full (GTK_OBJECT (Config), "GtkCombo_FRes", GtkCombo_FRes,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (GtkCombo_FRes);
  gtk_box_pack_start (GTK_BOX (hbox1), GtkCombo_FRes, FALSE, FALSE, 0);
  gtk_widget_set_usize (GtkCombo_FRes, 130, -2);

  combo_entry1 = GTK_COMBO (GtkCombo_FRes)->entry;
  gtk_widget_ref (combo_entry1);
  gtk_object_set_data_full (GTK_OBJECT (Config), "combo_entry1", combo_entry1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (combo_entry1);
  gtk_entry_set_editable (GTK_ENTRY (combo_entry1), FALSE);

  hbox6 = gtk_hbox_new (FALSE, 5);
  gtk_widget_ref (hbox6);
  gtk_object_set_data_full (GTK_OBJECT (Config), "hbox6", hbox6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox6);
  gtk_box_pack_start (GTK_BOX (vbox8), hbox6, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox6), 5);

  label6 = gtk_label_new ("Windowed Resolution");
  gtk_widget_ref (label6);
  gtk_object_set_data_full (GTK_OBJECT (Config), "label6", label6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox6), label6, FALSE, FALSE, 0);

  GtkCombo_WRes = gtk_combo_new ();
  gtk_widget_ref (GtkCombo_WRes);
  gtk_object_set_data_full (GTK_OBJECT (Config), "GtkCombo_WRes", GtkCombo_WRes,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (GtkCombo_WRes);
  gtk_box_pack_start (GTK_BOX (hbox6), GtkCombo_WRes, FALSE, FALSE, 0);
  gtk_widget_set_usize (GtkCombo_WRes, 130, -2);

  entry1 = GTK_COMBO (GtkCombo_WRes)->entry;
  gtk_widget_ref (entry1);
  gtk_object_set_data_full (GTK_OBJECT (Config), "entry1", entry1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (entry1);
  gtk_entry_set_editable (GTK_ENTRY (entry1), FALSE);

  frame1 = gtk_frame_new ("Options");
  gtk_widget_ref (frame1);
  gtk_object_set_data_full (GTK_OBJECT (Config), "frame1", frame1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame1);
  gtk_box_pack_start (GTK_BOX (vbox1), frame1, TRUE, TRUE, 0);

  table1 = gtk_table_new (3, 2, FALSE);
  gtk_widget_ref (table1);
  gtk_object_set_data_full (GTK_OBJECT (Config), "table1", table1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table1);
  gtk_container_add (GTK_CONTAINER (frame1), table1);
  gtk_container_set_border_width (GTK_CONTAINER (table1), 5);
  gtk_table_set_row_spacings (GTK_TABLE (table1), 5);
  gtk_table_set_col_spacings (GTK_TABLE (table1), 5);

  GtkCheckButton_Fps = gtk_check_button_new_with_label ("Display Fps Count");
  gtk_widget_ref (GtkCheckButton_Fps);
  gtk_object_set_data_full (GTK_OBJECT (Config), "GtkCheckButton_Fps", GtkCheckButton_Fps,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (GtkCheckButton_Fps);
  gtk_table_attach (GTK_TABLE (table1), GtkCheckButton_Fps, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  GtkCheckButton_Frameskip = gtk_check_button_new_with_label ("Enable Frameskip");
  gtk_widget_ref (GtkCheckButton_Frameskip);
  gtk_object_set_data_full (GTK_OBJECT (Config), "GtkCheckButton_Frameskip", GtkCheckButton_Frameskip,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (GtkCheckButton_Frameskip);
  gtk_table_attach (GTK_TABLE (table1), GtkCheckButton_Frameskip, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  GtkCheckButton_Fullscreen = gtk_check_button_new_with_label ("Enable Fullscreen");
  gtk_widget_ref (GtkCheckButton_Fullscreen);
  gtk_object_set_data_full (GTK_OBJECT (Config), "GtkCheckButton_Fullscreen", GtkCheckButton_Fullscreen,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (GtkCheckButton_Fullscreen);
  gtk_table_attach (GTK_TABLE (table1), GtkCheckButton_Fullscreen, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  GtkCheckButton_Stretch = gtk_check_button_new_with_label ("Disable Stretching");
  gtk_widget_ref (GtkCheckButton_Stretch);
  gtk_object_set_data_full (GTK_OBJECT (Config), "GtkCheckButton_Stretch", GtkCheckButton_Stretch,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (GtkCheckButton_Stretch);
  gtk_table_attach (GTK_TABLE (table1), GtkCheckButton_Stretch, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label7 = gtk_label_new ("Screen Filtering");
  gtk_widget_ref (label7);
  gtk_object_set_data_full (GTK_OBJECT (Config), "label7", label7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label7);
  gtk_table_attach (GTK_TABLE (table1), label7, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label7), 0, 0.5);

  GtkCombo_Filters = gtk_combo_new ();
  gtk_widget_ref (GtkCombo_Filters);
  gtk_object_set_data_full (GTK_OBJECT (Config), "GtkCombo_Filters", GtkCombo_Filters,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (GtkCombo_Filters);
  gtk_table_attach (GTK_TABLE (table1), GtkCombo_Filters, 1, 2, 2, 3,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_usize (GtkCombo_Filters, 120, -2);

  combo_entry4 = GTK_COMBO (GtkCombo_Filters)->entry;
  gtk_widget_ref (combo_entry4);
  gtk_object_set_data_full (GTK_OBJECT (Config), "combo_entry4", combo_entry4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (combo_entry4);

  vbox6 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox6);
  gtk_object_set_data_full (GTK_OBJECT (Config), "vbox6", vbox6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox6);
  gtk_box_pack_start (GTK_BOX (hbox5), vbox6, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (vbox6), 5);

  frame4 = gtk_frame_new ("Texture Caching");
  gtk_widget_ref (frame4);
  gtk_object_set_data_full (GTK_OBJECT (Config), "frame4", frame4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame4);
  gtk_box_pack_start (GTK_BOX (vbox6), frame4, TRUE, TRUE, 0);

  vbox5 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox5);
  gtk_object_set_data_full (GTK_OBJECT (Config), "vbox5", vbox5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox5);
  gtk_container_add (GTK_CONTAINER (frame4), vbox5);
  gtk_container_set_border_width (GTK_CONTAINER (vbox5), 5);

  GtkCheckButton_Cache = gtk_check_button_new_with_label ("Enable Texture Caching");
  gtk_widget_ref (GtkCheckButton_Cache);
  gtk_object_set_data_full (GTK_OBJECT (Config), "GtkCheckButton_Cache", GtkCheckButton_Cache,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (GtkCheckButton_Cache);
  gtk_box_pack_start (GTK_BOX (vbox5), GtkCheckButton_Cache, FALSE, FALSE, 0);

  hbox2 = gtk_hbox_new (FALSE, 5);
  gtk_widget_ref (hbox2);
  gtk_object_set_data_full (GTK_OBJECT (Config), "hbox2", hbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox2);
  gtk_box_pack_start (GTK_BOX (vbox5), hbox2, TRUE, TRUE, 0);

  label5 = gtk_label_new ("Cache Size");
  gtk_widget_ref (label5);
  gtk_object_set_data_full (GTK_OBJECT (Config), "label5", label5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox2), label5, FALSE, FALSE, 0);

  GtkCombo_CacheSize = gtk_combo_new ();
  gtk_widget_ref (GtkCombo_CacheSize);
  gtk_object_set_data_full (GTK_OBJECT (Config), "GtkCombo_CacheSize", GtkCombo_CacheSize,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (GtkCombo_CacheSize);
  gtk_box_pack_start (GTK_BOX (hbox2), GtkCombo_CacheSize, TRUE, FALSE, 0);
  gtk_widget_set_usize (GtkCombo_CacheSize, 80, -2);

  combo_entry2 = GTK_COMBO (GtkCombo_CacheSize)->entry;
  gtk_widget_ref (combo_entry2);
  gtk_object_set_data_full (GTK_OBJECT (Config), "combo_entry2", combo_entry2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (combo_entry2);

  GtkFrame_Rec = gtk_frame_new ("Recording");
  gtk_widget_ref (GtkFrame_Rec);
  gtk_object_set_data_full (GTK_OBJECT (Config), "GtkFrame_Rec", GtkFrame_Rec,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (GtkFrame_Rec);
  gtk_box_pack_start (GTK_BOX (vbox6), GtkFrame_Rec, TRUE, TRUE, 0);

  vbox7 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox7);
  gtk_object_set_data_full (GTK_OBJECT (Config), "vbox7", vbox7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox7);
  gtk_container_add (GTK_CONTAINER (GtkFrame_Rec), vbox7);
  gtk_container_set_border_width (GTK_CONTAINER (vbox7), 5);

  GtkCheckButton_Record = gtk_check_button_new_with_label ("Enable Recording");
  gtk_widget_ref (GtkCheckButton_Record);
  gtk_object_set_data_full (GTK_OBJECT (Config), "GtkCheckButton_Record", GtkCheckButton_Record,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (GtkCheckButton_Record);
  gtk_box_pack_start (GTK_BOX (vbox7), GtkCheckButton_Record, FALSE, FALSE, 0);

  GtkCombo_Codec = gtk_combo_new ();
  gtk_widget_ref (GtkCombo_Codec);
  gtk_object_set_data_full (GTK_OBJECT (Config), "GtkCombo_Codec", GtkCombo_Codec,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (GtkCombo_Codec);
  gtk_box_pack_start (GTK_BOX (vbox7), GtkCombo_Codec, FALSE, FALSE, 0);

  combo_entry3 = GTK_COMBO (GtkCombo_Codec)->entry;
  gtk_widget_ref (combo_entry3);
  gtk_object_set_data_full (GTK_OBJECT (Config), "combo_entry3", combo_entry3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (combo_entry3);

  hbuttonbox1 = gtk_hbutton_box_new ();
  gtk_widget_ref (hbuttonbox1);
  gtk_object_set_data_full (GTK_OBJECT (Config), "hbuttonbox1", hbuttonbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox1);
  gtk_box_pack_start (GTK_BOX (vbox4), hbuttonbox1, TRUE, TRUE, 0);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox1), GTK_BUTTONBOX_END);

  button1 = gtk_button_new_with_label ("Ok");
  gtk_widget_ref (button1);
  gtk_object_set_data_full (GTK_OBJECT (Config), "button1", button1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button1);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), button1);
  GTK_WIDGET_SET_FLAGS (button1, GTK_CAN_DEFAULT);

  button2 = gtk_button_new_with_label ("Cancel");
  gtk_widget_ref (button2);
  gtk_object_set_data_full (GTK_OBJECT (Config), "button2", button2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button2);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), button2);
  GTK_WIDGET_SET_FLAGS (button2, GTK_CAN_DEFAULT);

  GtkButton_Logging = gtk_button_new_with_label ("Logging...");
  gtk_widget_ref (GtkButton_Logging);
  gtk_object_set_data_full (GTK_OBJECT (Config), "GtkButton_Logging", GtkButton_Logging,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (GtkButton_Logging);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), GtkButton_Logging);
  GTK_WIDGET_SET_FLAGS (GtkButton_Logging, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (button1), "clicked",
                      GTK_SIGNAL_FUNC (OnConf_Ok),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button2), "clicked",
                      GTK_SIGNAL_FUNC (OnConf_Cancel),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (GtkButton_Logging), "clicked",
                      GTK_SIGNAL_FUNC (OnConf_Logging),
                      NULL);

  return Config;
}

GtkWidget*
create_About (void)
{
  GtkWidget *About;
  GtkWidget *vbox2;
  GtkWidget *label2;
  GtkWidget *label3;
  GtkWidget *label4;
  GtkWidget *hbuttonbox2;
  GtkWidget *button3;

  About = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (About), "About", About);
  gtk_container_set_border_width (GTK_CONTAINER (About), 5);
  gtk_window_set_title (GTK_WINDOW (About), "GSabout");
  gtk_window_set_position (GTK_WINDOW (About), GTK_WIN_POS_CENTER);

  vbox2 = gtk_vbox_new (FALSE, 5);
  gtk_widget_ref (vbox2);
  gtk_object_set_data_full (GTK_OBJECT (About), "vbox2", vbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox2);
  gtk_container_add (GTK_CONTAINER (About), vbox2);
  gtk_container_set_border_width (GTK_CONTAINER (vbox2), 5);

  label2 = gtk_label_new ("GSsoftx Driver");
  gtk_widget_ref (label2);
  gtk_object_set_data_full (GTK_OBJECT (About), "label2", label2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (vbox2), label2, FALSE, FALSE, 0);

  label3 = gtk_label_new ("Authors: linuzappz <linuzappz@hotmail.com>\n            [TyRaNiD]");
  gtk_widget_ref (label3);
  gtk_object_set_data_full (GTK_OBJECT (About), "label3", label3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (vbox2), label3, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label3), GTK_JUSTIFY_LEFT);

  label4 = gtk_label_new ("Thanks to:\n\t\tshadow - conding support and help.\n\t\tPete Bernert - for the triangles code.\n\t\tAbsolute0 - help fixing bugs :)");
  gtk_widget_ref (label4);
  gtk_object_set_data_full (GTK_OBJECT (About), "label4", label4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (vbox2), label4, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label4), GTK_JUSTIFY_LEFT);

  hbuttonbox2 = gtk_hbutton_box_new ();
  gtk_widget_ref (hbuttonbox2);
  gtk_object_set_data_full (GTK_OBJECT (About), "hbuttonbox2", hbuttonbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox2);
  gtk_box_pack_start (GTK_BOX (vbox2), hbuttonbox2, TRUE, TRUE, 0);

  button3 = gtk_button_new_with_label ("Ok");
  gtk_widget_ref (button3);
  gtk_object_set_data_full (GTK_OBJECT (About), "button3", button3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button3);
  gtk_container_add (GTK_CONTAINER (hbuttonbox2), button3);
  GTK_WIDGET_SET_FLAGS (button3, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (button3), "clicked",
                      GTK_SIGNAL_FUNC (OnAbout_Ok),
                      NULL);

  return About;
}

GtkWidget*
create_Logging (void)
{
  GtkWidget *Logging;
  GtkWidget *vbox3;
  GtkWidget *GtkCheckButton_Log;
  GtkWidget *hbuttonbox3;
  GtkWidget *button5;
  GtkWidget *button6;

  Logging = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (Logging), "Logging", Logging);
  gtk_container_set_border_width (GTK_CONTAINER (Logging), 5);
  gtk_window_set_title (GTK_WINDOW (Logging), "Logging");
  gtk_window_set_position (GTK_WINDOW (Logging), GTK_WIN_POS_CENTER);

  vbox3 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox3);
  gtk_object_set_data_full (GTK_OBJECT (Logging), "vbox3", vbox3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox3);
  gtk_container_add (GTK_CONTAINER (Logging), vbox3);

  GtkCheckButton_Log = gtk_check_button_new_with_label ("Log");
  gtk_widget_ref (GtkCheckButton_Log);
  gtk_object_set_data_full (GTK_OBJECT (Logging), "GtkCheckButton_Log", GtkCheckButton_Log,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (GtkCheckButton_Log);
  gtk_box_pack_start (GTK_BOX (vbox3), GtkCheckButton_Log, FALSE, FALSE, 0);

  hbuttonbox3 = gtk_hbutton_box_new ();
  gtk_widget_ref (hbuttonbox3);
  gtk_object_set_data_full (GTK_OBJECT (Logging), "hbuttonbox3", hbuttonbox3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox3);
  gtk_box_pack_start (GTK_BOX (vbox3), hbuttonbox3, TRUE, TRUE, 0);

  button5 = gtk_button_new_with_label ("Ok");
  gtk_widget_ref (button5);
  gtk_object_set_data_full (GTK_OBJECT (Logging), "button5", button5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button5);
  gtk_container_add (GTK_CONTAINER (hbuttonbox3), button5);
  GTK_WIDGET_SET_FLAGS (button5, GTK_CAN_DEFAULT);

  button6 = gtk_button_new_with_label ("Cancel");
  gtk_widget_ref (button6);
  gtk_object_set_data_full (GTK_OBJECT (Logging), "button6", button6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button6);
  gtk_container_add (GTK_CONTAINER (hbuttonbox3), button6);
  GTK_WIDGET_SET_FLAGS (button6, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (button5), "clicked",
                      GTK_SIGNAL_FUNC (OnLogging_Ok),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button6), "clicked",
                      GTK_SIGNAL_FUNC (OnLogging_Cancel),
                      NULL);

  return Logging;
}

