name: Feature request
description: If RPCS3 lacks a feature you would like to see
title: "[Feature request] Enter a title here"
labels: []
body:
  - type: markdown
    attributes:
      value: |
        Please do not ask for help or report compatibility regressions here, use [RPCS3 Discord server](https://discord.me/RPCS3) or [forums](https://forums.rpcs3.net/) instead.
  - type: textarea
    id: quick-summary
    attributes:
      label: Quick summary
      description: Please briefly describe what feature you would like RPCS3 to have.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Please include the following information:
        * What part of RPCS3 would be affected by your feature? (Gameplay, Debugging, UI, Patches, Installation, CI etc.)
        * Why your feature is important to RPCS3.
        * If the feature is implemented in other projects, attach screenshots.
  - type: textarea
    id: details
    attributes:
      label: Details
      description: Please describe the feature as accurately as possible.
    validations:
      required: false
