//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by LilyPad.rc
//
#define IDD_GENERAL                     102
#define IDD_ABOUT                       103
#define IDI_FROG                        104
#define IDD_CONFIG                      105
#define IDD_CONFIG_GUITAR               106
#define IDD_PROPPAGE_LARGE              107
#define IDC_CURSOR1                     107
#define IDC_ESCAPE_FULLSCREEN_HACK      107
#define IDD_DIAG                        109
#define IDC_CLOSE_HACK1                 1099
#define IDC_KB_DISABLE                  1100
#define IDC_KB_DI                       1101
#define IDC_KB_WM                       1102
#define IDC_KB_RAW                      1103
#define IDC_DISABLE_PAD1                1104
#define IDC_M_DISABLE                   1106
#define IDC_M_DI                        1107
#define IDC_M_WM                        1108
#define IDC_M_RAW                       1109
#define IDC_G_XI                        1110
#define IDC_G_DI                        1111
#define IDC_G_DS3                       1112
#define IDC_CLOSE_HACK2                 1113
#define IDC_DEBUG_FILE                  1114
#define IDC_GUITAR1                     1115
#define IDC_ANALOG_START1               1117
#define IDC_MULTITAP1                   1118
#define IDC_DISABLE_SCREENSAVER         1119
#define IDC_MOUSE_UNFOCUS               1120
#define IDC_AXIS_BUTTONS                1121
#define IDC_MULTITAP2                   1121
#define IDC_BACKGROUND                  1122
#define IDC_MULTIPLE_BINDING            1123
#define IDC_DISABLE_SCREENSAVER2        1124
#define IDC_FORCE_HIDE                  1124
#define IDC_GH2_HACK                    1125
#define IDC_FORCEFEEDBACK_HACK1         1126
#define IDC_VISTA_VOLUME                1126
#define IDC_SAVE_STATE_TITLE            1129
#define IDC_PAD_LIST                    1133
#define IDC_COMBO1                      1134
#define IDC_PAD_TYPE                    1134
#define IDC_SLIDER1                     0x1000
#define IDC_FLIP1                       0x1001
#define IDC_AXIS_DIRECTION              0x1002
#define IDC_AXIS_CONTROL1               0x1003
#define IDC_AXIS_SENSITIVITY1           0x1004
#define IDC_TURBO                       0x1005
#define IDC_AXIS_DEVICE1                0x1006
#define ID_SENSITIVITY                  0x1007
#define IDC_DPAD                        0x1008
#define IDC_LSTICK                      0x1009
#define IDC_RSTICK                      0x100A
#define IDC_SLIDER_DEADZONE             0x1010
#define IDC_AXIS_DEADZONE               0x1014
#define IDC_LABEL_SENSITIVITY           0x1020
#define IDC_LABEL_DEADZONE              0x1021
#define ID_LOCK_BUTTONS                 0x10FC
#define ID_LOCK                         0x10FD
#define ID_LOCK_DIRECTION               0x10FE
#define ID_MOUSE                        0x10FF
#define ID_SELECT                       0x1100
#define ID_L3                           0x1101
#define ID_R3                           0x1102
#define ID_START                        0x1103
#define ID_DPAD_UP                      0x1104
#define ID_DPAD_RIGHT                   0x1105
#define ID_DPAD_DOWN                    0x1106
#define ID_DPAD_LEFT                    0x1107
#define ID_L2                           0x1108
#define ID_R2                           0x1109
#define ID_L1                           0x110A
#define ID_R1                           0x110B
#define ID_TRIANGLE                     0x110C
#define ID_CIRCLE                       0x110D
#define ID_CROSS                        0x110E
#define ID_SQUARE                       0x110F
#define ID_LSTICK_UP                    0x1110
#define ID_LSTICK_RIGHT                 0x1111
#define ID_LSTICK_DOWN                  0x1112
#define ID_LSTICK_LEFT                  0x1113
#define ID_RSTICK_UP                    0x1114
#define ID_RSTICK_RIGHT                 0x1115
#define ID_RSTICK_DOWN                  0x1116
#define ID_RSTICK_LEFT                  0x1117
#define ID_ANALOG                       0x1118
#define ID_DELETE                       0x11FF
#define ID_DEBUG                        0x1200
#define ID_IGNORE                       0x1201
#define ID_CLEAR                        0x1202
#define ID_REFRESH                      0x1202
#define ID_SAVE                         0x1204
#define ID_LOAD                         0x1205
#define IDC_LIST                        0x1207
#define IDC_FORCEFEEDBACK               0x1208
#define IDC_FORCEFEEDBACK_FUNCTION      0x1209
#define ID_BIG_MOTOR                    0x120A
#define ID_SMALL_MOTOR                  0x120B
#define ID_TEST                         0x1300
#define ID_CONTROLS                     0x1301
#define IDC_FF_DEVICE                   0x1302
#define IDC_FF_MOTOR                    0x1303
#define ID_FF                           0x1304
#define IDC_FF_EFFECT                   0x1305
#define IDC_VERSION                     0x1306
#define IDC_FF_AXIS1_ENABLED            0x1310
#define IDC_FF_AXIS1                    0x1311
#define IDC_FF_AXIS1_FLIP               0x1312
#define IDC_FF_AXIS1_SCALE              0x1313
#define IDC_FF_AXIS2_ENABLED            0x1320
#define IDC_FF_AXIS2                    0x1321
#define IDC_FF_AXIS2_FLIP               0x1322
#define IDC_FF_AXIS2_SCALE              0x1323
#define IDC_FF_AXIS3_ENABLED            0x1330
#define IDC_FF_AXIS3                    0x1331
#define IDC_FF_AXIS3_FLIP               0x1332
#define IDC_FF_AXIS3_SCALE              0x1333
#define IDC_FF_AXIS4_ENABLED            0x1340
#define IDC_FF_AXIS4                    0x1341
#define IDC_FF_AXIS4_FLIP               0x1342
#define IDC_FF_AXIS4_SCALE              0x1343
#define IDC_FF_AXIS5_ENABLED            0x1350
#define IDC_FF_AXIS5                    0x1351
#define IDC_FF_AXIS5_FLIP               0x1352
#define IDC_FF_AXIS5_SCALE              0x1353
#define IDC_FF_AXIS6_ENABLED            0x1360
#define IDC_FF_AXIS6                    0x1361
#define IDC_FF_AXIS6_FLIP               0x1362
#define IDC_FF_AXIS6_SCALE              0x1363
#define IDC_FF_AXIS7_ENABLED            0x1370
#define IDC_FF_AXIS7                    0x1371
#define IDC_FF_AXIS7_FLIP               0x1372
#define IDC_FF_AXIS7_SCALE              0x1373
#define IDC_FF_AXIS8_ENABLED            0x1380
#define IDC_FF_AXIS8                    0x1381
#define IDC_FF_AXIS8_FLIP               0x1382
#define IDC_FF_AXIS8_SCALE              0x1383

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        112
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1135
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
