#pragma once

#include "util/types.hpp"
#include <string>
#include "stdafx.h"
#include "np_countries.h"
namespace countries
{
	constexpr std::vector<country_code> get_countries()
	{
		std::vector<country_code> countries =
		{
			{"United States", "us"},
			{"Japan", "jp"},
			{"Afghanistan", "af"},
			{"Albania", "al"},
			{"Algeria", "dz"},
			{"American Samoa", "as"},
			{"Andorra", "ad"},
			{"Angola", "ao"},
			{"Anguilla", "ai"},
			{"Antarctica", "aq"},
			{"Antigua & Barbuda", "ag"},
			{"Argentina", "ar"},
			{"Armenia", "am"},
			{"Aruba", "aw"},
			{"Australia", "au"},
			{"Austria", "at"},
			{"Azerbaijan", "az"},
			{"Bahamas", "bs"},
			{"Bahrain", "bh"},
			{"Bangladesh", "bd"},
			{"Barbados", "bb"},
			{"Belarus", "by"},
			{"Belgium", "be"},
			{"Belize", "bz"},
			{"Benin", "bj"},
			{"Bermuda", "bm"},
			{"Bhutan", "bt"},
			{"Bolivia", "bo"},
			{"Bosnia & Herzegovina", "ba"},
			{"Botswana", "bw"},
			{"Brazil", "br"},
			{"BIO Territory", "io"},
			{"British Virgin Islands", "vg"},
			{"Brunei", "bn"},
			{"Bulgaria", "bg"},
			{"Burkina Faso", "bf"},
			{"Burundi", "bi"},
			{"Cambodia", "kh"},
			{"Cameroon", "cm"},
			{"Canada", "ca"},
			{"Cape Verde", "cv"},
			{"Cayman Islands", "ky"},
			{"Central African Republic", "cf"},
			{"Chad", "td"},
			{"Chile", "cl"},
			{"China", "cn"},
			{"Christmas Island", "cx"},
			{"Cocos Islands", "cc"},
			{"Colombia", "co"},
			{"Comoros", "km"},
			{"Congo", "cg"},
			{"Cook Islands", "ck"},
			{"Costa Rica", "cr"},
			{"Croatia", "hr"},
			{"Cuba", "cu"},
			{"Curacao", "cw"},
			{"Cyprus", "cy"},
			{"Czech Republic", "cz"},
			{"DRcongo", "cd"},
			{"Denmark", "dk"},
			{"Djibouti", "dj"},
			{"Dominica", "dm"},
			{"Dominican Republic", "do"},
			{"East Timor", "tl"},
			{"Ecuador", "ec"},
			{"Egypt", "eg"},
			{"El Salvador", "sv"},
			{"Equatorial Guinea", "gq"},
			{"Eritrea", "er"},
			{"Estonia", "ee"},
			{"Eswatini", "sz"},
			{"Ethiopia", "et"},
			{"Faroe Islands", "fo"},
			{"Fiji", "fj"},
			{"Finland", "fi"},
			{"France", "fr"},
			{"French Polynesia", "pf"},
			{"Gabon", "ga"},
			{"Gambia", "gm"},
			{"Georgia", "ge"},
			{"Germany", "de"},
			{"Ghana", "gh"},
			{"Gibraltar", "gi"},
			{"Greece", "gr"},
			{"Greenland", "gl"},
			{"Grenada", "gd"},
			{"Guam", "gu"},
			{"Guatemala", "gt"},
			{"Guernsey", "gg"},
			{"Guinea", "gn"},
			{"Guinea-Bissau", "gw"},
			{"Guyana", "gy"},
			{"Haiti", "ht"},
			{"Honduras", "hn"},
			{"Hong Kong", "hk"},
			{"Hungary", "hu"},
			{"Iceland", "is"},
			{"India", "in"},
			{"Indonesia", "id"},
			{"Iran", "ir"},
			{"Iraq", "iq"},
			{"Ireland", "ie"},
			{"Isle of Man", "im"},
			{"Israel", "il"},
			{"Italy", "it"},
			{"Ivorycoast", "ci"},
			{"Jamaica", "jm"},
			{"Jersey", "je"},
			{"Jordan", "jo"},
			{"Kazakhstan", "kz"},
			{"Kenya", "ke"},
			{"Kiribati", "ki"},
			{"Kosovo", "xk"},
			{"Kuwait", "kw"},
			{"Kyrgyzstan", "kg"},
			{"Laos", "la"},
			{"Latvia", "lv"},
			{"Lebanon", "lb"},
			{"Lesotho", "ls"},
			{"Liberia", "lr"},
			{"Libya", "ly"},
			{"Liechtenstein", "li"},
			{"Lithuania", "lt"},
			{"Luxembourg", "lu"},
			{"Macao", "mo"},
			{"Madagascar", "mg"},
			{"Malawi", "mw"},
			{"Malaysia", "my"},
			{"Maldives", "mv"},
			{"Mali", "ml"},
			{"Malta", "mt"},
			{"Marshall Islands", "mh"},
			{"Mauritania", "mr"},
			{"Mauritius", "mu"},
			{"Mayotte", "yt"},
			{"Mexico", "mx"},
			{"Micronesia", "fm"},
			{"Moldova", "md"},
			{"Monaco", "mc"},
			{"Mongolia", "mn"},
			{"Montenegro", "me"},
			{"Montserrat", "ms"},
			{"Morocco", "ma"},
			{"Mozambique", "mz"},
			{"Myanmar", "mm"},
			{"Namibia", "na"},
			{"Nauru", "nr"},
			{"Nepal", "np"},
			{"Netherlands", "nl"},
			{"Netherlands Antilles", "an"},
			{"Newcaledonia", "nc"},
			{"New Zealand", "nz"},
			{"Nicaragua", "ni"},
			{"Niger", "ne"},
			{"Nigeria", "ng"},
			{"Niue", "nu"},
			{"North Korea", "kp"},
			{"Northern Mariana Islands", "mp"},
			{"Norway", "no"},
			{"Oman", "om"},
			{"Pakistan", "pk"},
			{"Palau", "pw"},
			{"Palestine", "ps"},
			{"Panama", "pa"},
			{"Papua New Guinea", "pg"},
			{"Paraguay", "py"},
			{"Peru", "pe"},
			{"Philippines", "ph"},
			{"Pitcairn", "pn"},
			{"Poland", "pl"},
			{"Portugal", "pt"},
			{"Puerto Rico", "pr"},
			{"Qatar", "qa"},
			{"Reunion", "re"},
			{"Romania", "ro"},
			{"Russia", "ru"},
			{"Rwanda", "rw"},
			{"St Barthelemy", "bl"},
			{"St Helena", "sh"},
			{"St Kitts & Nevis", "kn"},
			{"St Lucia", "lc"},
			{"St Martin", "mf"},
			{"St Pierre & Miquelon", "pm"},
			{"St Vincent & the Grenadines", "vc"},
			{"Samoa", "ws"},
			{"San Marino", "sm"},
			{"Sao Tome & Principe", "st"},
			{"Saudi Arabia", "sa"},
			{"Senegal", "sn"},
			{"Serbia", "rs"},
			{"Seychelles", "sc"},
			{"Sierra Leone", "sl"},
			{"Singapore", "sg"},
			{"Sint Maarten", "sx"},
			{"Slovakia", "sk"},
			{"Slovenia", "si"},
			{"Solomon Islands", "sb"},
			{"Somalia", "so"},
			{"South Africa", "za"},
			{"South Georgia & South Sandwich Islands", "gs"},
			{"South Korea", "kr"},
			{"South Sudan", "ss"},
			{"Spain", "es"},
			{"Sri Lanka", "lk"},
			{"Sudan", "sd"},
			{"Suriname", "sr"},
			{"Svalbard & Jan Mayen", "sj"},
			{"Sweden", "se"},
			{"Switzerland", "ch"},
			{"Syria", "sy"},
			{"Taiwan", "tw"},
			{"Tajikistan", "tj"},
			{"Tanzania", "tz"},
			{"Thailand", "th"},
			{"Togo", "tg"},
			{"Tokelau", "tk"},
			{"Tonga", "to"},
			{"Trinidad & Tobago", "tt"},
			{"Tunisia", "tn"},
			{"Turkey", "tr"},
			{"Turkmenistan", "tm"},
			{"Turks &caicos Islands", "tc"},
			{"Tuvalu", "tv"},
			{"Uganda", "ug"},
			{"Ukraine", "ua"},
			{"United Arab Emirates", "ae"},
			{"United Kingdom", "gb"},
			{"Uruguay", "uy"},
			{"Uzbekistan", "uz"},
			{"Vanuatu", "vu"},
			{"Vaticancity", "va"},
			{"Venezuela", "ve"},
			{"Vietnam", "vn"},
			{"Western Sahara", "eh"},
			{"Yemen", "ye"},
			{"Zambia", "zm"},
			{"Zimbabwe", "zw"}
		};

		return countries;
	}
} // namespace countries