#pragma once

enum SceVoiceQoSAttributeId : s32
{
	SCE_VOICE_QOS_ATTR_MIC_VOLUME,
	SCE_VOICE_QOS_ATTR_MIC_MUTE,
	SCE_VOICE_QOS_ATTR_SPEAKER_VOLUME,
	SCE_VOICE_QOS_ATTR_SPEAKER_MUTE,
	SCE_VOICE_QOS_ATTR_DESIRED_OUT_BIT_RATE
};

enum SceVoiceQoSStatusId : s32
{
	SCE_VOICE_QOS_IN_BITRATE,
	SCE_VOICE_QOS_OUT_BITRATE,
	SCE_VOICE_QOS_OUT_READ_BITRATE,
	SCE_VOICE_QOS_IN_FRAME_RECEIVED_RATIO,
	SCE_VOICE_QOS_HEARTBEAT_FLAG
};

extern psv_log_base sceVoiceQoS;
