#pragma once

enum class emu_settings_type
{
	// Core
	PPUDecoder,
	SPUDecoder,
	LibLoadOptions,
	HookStaticFuncs,
	EnableThreadScheduler,
	LowerSPUThreadPrio,
	SPULoopDetection,
	PreferredSPUThreads,
	PPUDebug,
	SPUDebug,
	MaxLLVMThreads,
	EnableTSX,
	AccurateGETLLAR,
	AccuratePUTLLUC,
	AccuratePPUfma,
	AccurateRSXAccess,
	AccurateXFloat,
	SetDAZandFTZ,
	SPUBlockSize,
	SPUCache,
	DebugConsoleMode,
	SilenceAllLogs,
	MaxSPURSThreads,
	SleepTimersAccuracy,
	ClocksScale,

	// Graphics
	Renderer,
	Resolution,
	AspectRatio,
	FrameLimit,
	MSAA,
	LogShaderPrograms,
	WriteDepthBuffer,
	WriteColorBuffers,
	ReadColorBuffers,
	ReadDepthBuffer,
	VSync,
	DebugOutput,
	DebugOverlay,
	LegacyBuffers,
	GPUTextureScaling,
	StretchToDisplayArea,
	VulkanAdapter,
	ForceHighpZ,
	StrictRenderingMode,
	DisableVertexCache,
	DisableOcclusionQueries,
	DisableFIFOReordering,
	StrictTextureFlushing,
	AnisotropicFilterOverride,
	ResolutionScale,
	MinimumScalableDimension,
	ForceCPUBlitEmulation,
	DisableOnDiskShaderCache,
	DisableVulkanMemAllocator,
	DisableAsyncShaderCompiler,
	MultithreadedRSX,
	VBlankRate,
	RelaxedZCULL,
	DriverWakeUpDelay,

	// Performance Overlay
	PerfOverlayEnabled,
	PerfOverlayFramerateGraphEnabled,
	PerfOverlayFrametimeGraphEnabled,
	PerfOverlayDetailLevel,
	PerfOverlayPosition,
	PerfOverlayUpdateInterval,
	PerfOverlayFontSize,
	PerfOverlayOpacity,
	PerfOverlayMarginX,
	PerfOverlayMarginY,
	PerfOverlayCenterX,
	PerfOverlayCenterY,

	// Shader Loading Dialog
	ShaderLoadBgEnabled,
	ShaderLoadBgDarkening,
	ShaderLoadBgBlur,

	// Audio
	AudioRenderer,
	DumpToFile,
	ConvertTo16Bit,
	DownmixStereo,
	MasterVolume,
	EnableBuffering,
	AudioBufferDuration,
	EnableTimeStretching,
	TimeStretchingThreshold,
	MicrophoneType,
	MicrophoneDevices,

	// Input / Output
	PadHandler,
	KeyboardHandler,
	MouseHandler,
	Camera,
	CameraType,
	Move,

	// Misc
	ExitRPCS3OnFinish,
	StartOnBoot,
	StartGameFullscreen,
	PreventDisplaySleep,
	ShowTrophyPopups,
	ShowWelcomeScreen,
	UseNativeInterface,
	ShowShaderCompilationHint,
	WindowTitleFormat,

	// Network
	InternetStatus,
	DNSAddress,
	IpSwapList,
	PSNStatus,
	PSNNPID,

	// System
	Language,
	KeyboardType,
	EnterButtonAssignment,
	EnableHostRoot,
	LimitCacheSize,
	MaximumCacheSize,

	// Virtual File System
	emulatorLocation,
	dev_hdd0Location,
	dev_hdd1Location,
	dev_flashLocation,
	dev_usb000Location,
};
