#include "iso_test_fixture.h"
#include "Loader/CHD.h"

#include <atomic>
#include <cstdlib>
#include <thread>

namespace
{
	// Minimal uncompressed CHDv5. Compressed fixtures are generated by chdman
	// outside the test process, keeping the production reader under test here.
	std::vector<u8> wrap_chd(const std::vector<u8>& image, u32 hunk)
	{
		const u32 hunks = (image.size() + hunk - 1) / hunk;
		const u32 first = (124 + hunks * 4 + hunk - 1) / hunk;
		std::vector<u8> bytes((first + hunks) * hunk);
		auto big = [&](usz offset, u64 value, usz width)
		{
			for (usz i = 0; i < width; i++)
			{
				bytes[offset + width - i - 1] = value >> (8 * i);
			}
		};
		std::memcpy(bytes.data(), "MComprHD", 8);
		big(8, 124, 4);
		big(12, 5, 4);
		big(32, image.size(), 8);
		big(40, 124, 8);
		big(56, hunk, 4);
		big(60, 2048, 4);
		for (u32 i = 0; i < hunks; i++)
		{
			big(124 + i * 4, first + i, 4);
		}
		std::copy(image.begin(), image.end(), bytes.begin() + first * hunk);
		return bytes;
	}

	void save(const std::string& path, const std::vector<u8>& bytes)
	{
		std::ofstream out(path, std::ios::binary);
		out.write(reinterpret_cast<const char*>(bytes.data()), bytes.size());
		ASSERT_TRUE(out.good());
	}

	class observed_source final : public fs::file_base
	{
		fs::file m_file;
		u64& m_reads;
		bool& m_fail;
	public:
		observed_source(const std::string& path, u64& reads, bool& fail)
			: m_file(path), m_reads(reads), m_fail(fail)
		{
		}

		bool trunc(u64) override
		{
			return false;
		}

		u64 write(const void*, u64) override
		{
			return 0;
		}

		u64 read(void*, u64) override
		{
			ADD_FAILURE() << "Backing cursor read";
			return 0;
		}

		u64 seek(s64, fs::seek_mode) override
		{
			ADD_FAILURE() << "Backing cursor seek";
			return umax;
		}

		u64 size() override
		{
			return m_file.size();
		}

		u64 read_at(u64 offset, void* buffer, u64 count) override
		{
			m_reads++;
			if (m_fail)
			{
				std::memset(buffer, 0xee, count);
				return 0;
			}
			return m_file.read_at(offset, buffer, count);
		}
	};
}

TEST_F(iso_test, ChdBoundariesAndMountedLifetime)
{
	m_image.resize(25 * ISO_SECTOR_SIZE); // Logical EOF is inside the last hunk.
	for (u32 hunk : {4096u, 128u * 1024})
	{
		SCOPED_TRACE(hunk);
		const auto chd_path = (m_directory / "disc.chd").string();
		save(chd_path, wrap_chd(m_image, hunk));
		fs::file decoded(open_chd_image(fs::file(chd_path), chd_path));
		ASSERT_TRUE(decoded);
		ASSERT_EQ(decoded.size(), m_image.size());
		for (u64 offset : {0ull, 2047ull, 4095ull, 49151ull, 51199ull, 51200ull, ~0ull})
		{
			std::vector<u8> data(4099, 0x5a);
			const u64 expected = offset < m_image.size() ? std::min<u64>(data.size(), m_image.size() - offset) : 0;
			ASSERT_EQ(decoded.read_at(offset, data.data(), data.size()), expected);
			if (expected)
			{
				EXPECT_TRUE(std::equal(data.begin(), data.begin() + expected, m_image.begin() + offset));
			}
			EXPECT_TRUE(std::all_of(data.begin() + expected, data.end(), [](u8 b)
			{
				return b == 0x5a;
			}));
		}

		u64 logical_size = 0;
		EXPECT_TRUE(is_iso_file(chd_path, &logical_size));
		EXPECT_EQ(logical_size, m_image.size());
		fs::file member;
		{
			iso_archive archive(chd_path);
			ASSERT_TRUE(archive.is_valid());
			member = fs::file(archive.open("TEST.BIN"));
		}
		ASSERT_TRUE(member);
		std::array<char, 3> data{};
		EXPECT_EQ(member.read(data.data(), data.size()), data.size());
		EXPECT_EQ(std::string(data.data(), data.size()), "abc");
	}
}

TEST_F(iso_test, ChdReusesHunkAndInvalidatesItOnFailure)
{
	const auto chd_path = (m_directory / "cache.chd").string();
	save(chd_path, wrap_chd(m_image, 4096));
	u64 reads = 0;
	bool fail = false;
	fs::file source(std::make_unique<observed_source>(chd_path, reads, fail));
	fs::file decoded(open_chd_image(std::move(source), chd_path));
	ASSERT_TRUE(decoded);
	std::array<u8, 2048> data{};
	ASSERT_EQ(decoded.read_at(0, data.data(), data.size()), data.size());
	const auto first_reads = reads;
	ASSERT_EQ(decoded.read_at(2048, data.data(), data.size()), data.size());
	EXPECT_EQ(reads, first_reads);
	fail = true;
	data.fill(0x5a);
	EXPECT_EQ(decoded.read_at(4096, data.data(), data.size()), 0);
	EXPECT_EQ(fs::g_tls_error, fs::error::unknown);
	EXPECT_TRUE(std::all_of(data.begin(), data.end(), [](u8 b)
	{
		return b == 0x5a;
	}));
	fail = false;
	ASSERT_EQ(decoded.read_at(0, data.data(), data.size()), data.size());
	EXPECT_GT(reads, first_reads + 1);
	EXPECT_TRUE(std::equal(data.begin(), data.end(), m_image.begin()));
	fail = true;
	std::array<u8, 8192> crossing;
	crossing.fill(0x5a);
	EXPECT_EQ(decoded.read_at(0, crossing.data(), crossing.size()), 0);
	EXPECT_EQ(fs::g_tls_error, fs::error::unknown);
	EXPECT_TRUE(std::equal(crossing.begin(), crossing.begin() + 4096, m_image.begin()));
	EXPECT_TRUE(std::all_of(crossing.begin() + 4096, crossing.end(), [](u8 b)
	{
		return b == 0x5a;
	}));
}

TEST_F(iso_test, ChdConcurrentCursorAndPositionalReads)
{
	const auto chd_path = (m_directory / "threads.chd").string();
	for (usz i = 0; i < m_image.size(); i++)
	{
		m_image[i] = i % 251;
	}
	save(chd_path, wrap_chd(m_image, 4096));
	fs::file decoded(open_chd_image(fs::file(chd_path), chd_path));
	ASSERT_TRUE(decoded);
	std::array<std::atomic<u32>, 251> counts{};
	std::vector<std::thread> threads;
	for (u32 t = 0; t < 4; t++)
	{
		threads.emplace_back([&]
		{
			u8 byte = 0;
			while (decoded.read(&byte, 1))
			{
				counts[byte]++;
			}
		});
	}
	threads.emplace_back([&]
	{
		std::array<u8, 3073> data{};
		for (u32 i = 0; i < 200; i++)
		{
			const u64 offset = (i * 7919) % (m_image.size() - data.size());
			EXPECT_EQ(decoded.read_at(offset, data.data(), data.size()), data.size());
			EXPECT_TRUE(std::equal(data.begin(), data.end(), m_image.begin() + offset));
		}
	});
	for (auto& thread : threads)
	{
		thread.join();
	}
	for (u32 i = 0; i < counts.size(); i++)
	{
		EXPECT_EQ(counts[i], m_image.size() / 251 + (i < m_image.size() % 251));
	}
	EXPECT_EQ(decoded.pos(), m_image.size());
}

TEST_F(iso_test, ChdRejectsUnsupportedHeadersAndEncryption)
{
	const auto chd_path = (m_directory / "invalid.chd").string();
	for (usz field : {usz{15}, usz{60}, usz{104}, usz{16}})
	{
		auto bytes = wrap_chd(m_image, 4096);
		bytes[field] ^= 1; // Version, unit geometry, parent SHA1, unknown codec.
		save(chd_path, bytes);
		EXPECT_FALSE(open_chd_image(fs::file(chd_path), chd_path));
	}
	std::memcpy(m_image.data() + 0xF70, "Encrypted 3K BLD", 16);
	save(chd_path, wrap_chd(m_image, 4096));
	iso_archive encrypted(chd_path);
	EXPECT_FALSE(encrypted.is_valid());
	std::fill_n(m_image.data() + 0xF70, 16, 0);
	save(chd_path, wrap_chd(m_image, 4096));
	{
		std::ofstream key((m_directory / "invalid.dkey").string());
		key << "00000000000000000000000000000000";
	}
	iso_archive decrypted(chd_path);
	ASSERT_TRUE(decrypted.is_valid());
	fs::file member(decrypted.open("TEST.BIN"));
	char byte = 0;
	EXPECT_EQ(member.read(&byte, 1), 1);
	EXPECT_EQ(byte, 'a');
}

TEST_F(iso_test, ChdRejectsInvalidInnerIso)
{
	const auto chd_path = (m_directory / "not-iso.chd").string();
	m_image[16 * ISO_SECTOR_SIZE + 1] = 'X';
	save(chd_path, wrap_chd(m_image, 4096));
	EXPECT_TRUE(open_chd_image(fs::file(chd_path), chd_path));
	EXPECT_FALSE(is_iso_file(chd_path));
	iso_archive archive(chd_path);
	EXPECT_FALSE(archive.is_valid());
}

TEST_F(iso_test, ChdUnreadableDirectoryRejectsArchive)
{
	const auto chd_path = (m_directory / "truncated.chd").string();
	auto bytes = wrap_chd(m_image, 4096);
	// Keep the descriptors readable, but truncate the directory's hunk.
	bytes.resize(bytes.size() - 6 * ISO_SECTOR_SIZE + 10);
	save(chd_path, bytes);
	ASSERT_TRUE(open_chd_image(fs::file(chd_path), chd_path));
	iso_archive archive(chd_path);
	EXPECT_FALSE(archive.is_valid());
}

TEST_F(iso_test, ChdUnreadableDescriptorRejectsArchive)
{
	const auto chd_path = (m_directory / "descriptor.chd").string();
	auto bytes = wrap_chd(m_image, ISO_SECTOR_SIZE);
	// The probe and primary descriptor remain readable. The terminator points
	// beyond the physical file, so descriptor scanning encounters a read error.
	std::fill_n(bytes.begin() + 124 + 17 * 4, 4, 0xff);
	save(chd_path, bytes);
	ASSERT_TRUE(is_iso_file(chd_path));
	iso_archive archive(chd_path);
	EXPECT_FALSE(archive.is_valid());
}

TEST_F(iso_test, ChdCorruptCompressedHunkNeverReachesCaller)
{
	const char* fixture_dir = std::getenv("RPCS3_CHD_FIXTURES");
	if (!fixture_dir)
	{
		GTEST_SKIP() << "Requires generated compressed fixtures";
	}
	const auto fixture = std::filesystem::path(fixture_dir) / "zlib-4096.chd";
	if (!std::filesystem::exists(fixture))
	{
		GTEST_SKIP() << "Requires zlib-4096.chd";
	}
	fs::file input(fixture.string());
	std::vector<u8> bytes(input.size());
	ASSERT_EQ(input.read(bytes.data(), bytes.size()), bytes.size());
	ASSERT_GT(bytes.size(), 124);
	// createraw writes the first compressed payload immediately after the header.
	bytes[124] ^= 0xff;
	const auto corrupt = (m_directory / "corrupt.chd").string();
	save(corrupt, bytes);
	fs::file decoded(open_chd_image(fs::file(corrupt), corrupt));
	ASSERT_TRUE(decoded); // Header/map remain readable; failure is during decoding.
	std::array<u8, 4096> data;
	data.fill(0x5a);
	EXPECT_EQ(decoded.read_at(0, data.data(), data.size()), 0);
	EXPECT_EQ(fs::g_tls_error, fs::error::unknown);
	EXPECT_TRUE(std::all_of(data.begin(), data.end(), [](u8 b)
	{
		return b == 0x5a;
	}));
	EXPECT_EQ(decoded.read_at(0, data.data(), data.size()), 0);
}

TEST_F(iso_test, ChdUnicodePathAndContentDetection)
{
	const auto path = m_directory / std::filesystem::path(u8"disc-\u65e5\u672c\u8a9e-\u00e9.data");
	const auto utf8 = path.u8string();
	const std::string name(reinterpret_cast<const char*>(utf8.data()), utf8.size());
	const auto bytes = wrap_chd(m_image, 4096);
	{
		fs::file output(name, fs::rewrite);
		ASSERT_TRUE(output);
		ASSERT_EQ(output.write(bytes.data(), bytes.size()), bytes.size());
	}
	EXPECT_FALSE(is_chd_image(fs::file(m_path)));
	EXPECT_TRUE(is_chd_image(fs::file(name)));
	u64 size = 0;
	ASSERT_TRUE(is_iso_file(name, &size));
	EXPECT_EQ(size, m_image.size());
	iso_archive archive(name);
	ASSERT_TRUE(archive.is_valid());
	fs::file member(archive.open("TEST.BIN"));
	ASSERT_TRUE(member);
	char byte = 0;
	ASSERT_EQ(member.read(&byte, 1), 1);
	EXPECT_EQ(byte, 'a');
}

TEST_F(iso_test, ChdExternalCompressedFixtures)
{
	const char* fixture_dir = std::getenv("RPCS3_CHD_FIXTURES");
	if (!fixture_dir)
	{
		GTEST_SKIP() << "Set RPCS3_CHD_FIXTURES to the generated chdman fixture directory";
	}
	u32 tested = 0;
	for (const auto& entry : std::filesystem::directory_iterator(fixture_dir))
	{
		if (entry.path().extension() != ".chd")
		{
			continue;
		}
		SCOPED_TRACE(entry.path().string());
		auto iso_path = entry.path();
		iso_path.replace_extension(".iso");
		fs::file raw(iso_path.string());
		ASSERT_TRUE(raw);
		fs::file decoded(open_chd_image(fs::file(entry.path().string()), entry.path().string()));
		ASSERT_TRUE(decoded);
		ASSERT_EQ(decoded.size(), raw.size());
		std::vector<u8> expected(128 * 1024), actual(expected.size());
		for (u64 offset = 0; offset < raw.size();)
		{
			// Sector-sized requests exercise cross-call hunk reuse on compressed data.
			const u64 count = std::min<u64>(2048, raw.size() - offset);
			ASSERT_EQ(raw.read_at(offset, expected.data(), count), count);
			ASSERT_EQ(decoded.read_at(offset, actual.data(), count), count);
			ASSERT_TRUE(std::equal(expected.begin(), expected.begin() + count, actual.begin()));
			offset += count;
		}
		iso_archive archive(entry.path().string());
		ASSERT_TRUE(archive.is_valid());
		tested++;
	}
	EXPECT_GT(tested, 0);
}
