#pragma once

enum DInputKeyCodes
{
	NONE,
	POV_1_LEFT,
	POV_1_RIGHT,
	POV_1_UP,
	POV_1_DOWN,
	POV_2_LEFT,
	POV_2_RIGHT,
	POV_2_UP,
	POV_2_DOWN,
	POV_3_LEFT,
	POV_3_RIGHT,
	POV_3_UP,
	POV_3_DOWN,
	POV_4_LEFT,
	POV_4_RIGHT,
	POV_4_UP,
	POV_4_DOWN,
	AXIS_X_NEG,
	AXIS_X_POS,
	AXIS_Y_NEG,
	AXIS_Y_POS,
	AXIS_Z_NEG,
	AXIS_Z_POS,
	AXIS_X_ROT_NEG,
	AXIS_X_ROT_POS,
	AXIS_Y_ROT_NEG,
	AXIS_Y_ROT_POS,
	AXIS_Z_ROT_NEG,
	AXIS_Z_ROT_POS,
	// TODO: Add axis x,y,z velocity, acceleration etc ...
	SLIDER_1_NEG,
	SLIDER_1_POS,
	SLIDER_2_NEG,
	SLIDER_2_POS,
	SLIDER_1_VEL_NEG,
	SLIDER_1_VEL_POS,
	SLIDER_2_VEL_NEG,
	SLIDER_2_VEL_POS,
	SLIDER_1_ACC_NEG,
	SLIDER_1_ACC_POS,
	SLIDER_2_ACC_NEG,
	SLIDER_2_ACC_POS,
	SLIDER_1_FOR_NEG,
	SLIDER_1_FOR_POS,
	SLIDER_2_FOR_NEG,
	SLIDER_2_FOR_POS,
	BUTTON_1,
	BUTTON_2,
	BUTTON_3,
	BUTTON_4,
	BUTTON_5,
	BUTTON_6,
	BUTTON_7,
	BUTTON_8,
	BUTTON_9,
	BUTTON_10,
	BUTTON_11,
	BUTTON_12,
	BUTTON_13,
	BUTTON_14,
	BUTTON_15,
	BUTTON_16,
	BUTTON_17,
	BUTTON_18,
	BUTTON_19,
	BUTTON_20,
	BUTTON_21,
	BUTTON_22,
	BUTTON_23,
	BUTTON_24,
	BUTTON_25,
	BUTTON_26,
	BUTTON_27,
	BUTTON_28,
	BUTTON_29,
	BUTTON_30,
	BUTTON_31,
	BUTTON_32,
	BUTTON_33,
	BUTTON_34,
	BUTTON_35,
	BUTTON_36,
	BUTTON_37,
	BUTTON_38,
	BUTTON_39,
	BUTTON_40,
	BUTTON_41,
	BUTTON_42,
	BUTTON_43,
	BUTTON_44,
	BUTTON_45,
	BUTTON_46,
	BUTTON_47,
	BUTTON_48,
	BUTTON_49,
	BUTTON_50,
	BUTTON_51,
	BUTTON_52,
	BUTTON_53,
	BUTTON_54,
	BUTTON_55,
	BUTTON_56,
	BUTTON_57,
	BUTTON_58,
	BUTTON_59,
	BUTTON_60,
	BUTTON_61,
	BUTTON_62,
	BUTTON_63,
	BUTTON_64,
	BUTTON_65,
	BUTTON_66,
	BUTTON_67,
	BUTTON_68,
	BUTTON_69,
	BUTTON_70,
	BUTTON_71,
	BUTTON_72,
	BUTTON_73,
	BUTTON_74,
	BUTTON_75,
	BUTTON_76,
	BUTTON_77,
	BUTTON_78,
	BUTTON_79,
	BUTTON_80,
	BUTTON_81,
	BUTTON_82,
	BUTTON_83,
	BUTTON_84,
	BUTTON_85,
	BUTTON_86,
	BUTTON_87,
	BUTTON_88,
	BUTTON_89,
	BUTTON_90,
	BUTTON_91,
	BUTTON_92,
	BUTTON_93,
	BUTTON_94,
	BUTTON_95,
	BUTTON_96,
	BUTTON_97,
	BUTTON_98,
	BUTTON_99,
	BUTTON_100,
	BUTTON_101,
	BUTTON_102,
	BUTTON_103,
	BUTTON_104,
	BUTTON_105,
	BUTTON_106,
	BUTTON_107,
	BUTTON_108,
	BUTTON_109,
	BUTTON_110,
	BUTTON_111,
	BUTTON_112,
	BUTTON_113,
	BUTTON_114,
	BUTTON_115,
	BUTTON_116,
	BUTTON_117,
	BUTTON_118,
	BUTTON_119,
	BUTTON_120,
	BUTTON_121,
	BUTTON_122,
	BUTTON_123,
	BUTTON_124,
	BUTTON_125,
	BUTTON_126,
	BUTTON_127,
	BUTTON_128
};

static const std::unordered_map<u32, std::string> input_names =
{
	{ DInputKeyCodes::NONE,             ""               },
	{ DInputKeyCodes::POV_1_LEFT,       "POV 1 LEFT"     },
	{ DInputKeyCodes::POV_1_RIGHT,      "POV 1 RIGHT"    },
	{ DInputKeyCodes::POV_1_UP,         "POV 1 UP"       },
	{ DInputKeyCodes::POV_1_DOWN,       "POV 1 DOWN"     },
	{ DInputKeyCodes::POV_2_LEFT,       "POV 2 LEFT"     },
	{ DInputKeyCodes::POV_2_RIGHT,      "POV 2 RIGHT"    },
	{ DInputKeyCodes::POV_2_UP,         "POV 2 UP"       },
	{ DInputKeyCodes::POV_2_DOWN,       "POV 2 DOWN"     },
	{ DInputKeyCodes::POV_3_LEFT,       "POV 3 LEFT"     },
	{ DInputKeyCodes::POV_3_RIGHT,      "POV 3 RIGHT"    },
	{ DInputKeyCodes::POV_3_UP,         "POV 3 UP"       },
	{ DInputKeyCodes::POV_3_DOWN,       "POV 3 DOWN"     },
	{ DInputKeyCodes::POV_4_LEFT,       "POV 4 LEFT"     },
	{ DInputKeyCodes::POV_4_RIGHT,      "POV 4 RIGHT"    },
	{ DInputKeyCodes::POV_4_UP,         "POV 4 UP"       },
	{ DInputKeyCodes::POV_4_DOWN,       "POV 4 DOWN"     },
	{ DInputKeyCodes::AXIS_X_NEG,       "X -"            },
	{ DInputKeyCodes::AXIS_X_POS,       "X +"            },
	{ DInputKeyCodes::AXIS_Y_NEG,       "Y -"            },
	{ DInputKeyCodes::AXIS_Y_POS,       "Y +"            },
	{ DInputKeyCodes::AXIS_Z_NEG,       "Z -"            },
	{ DInputKeyCodes::AXIS_Z_POS,       "Z +"            },
	{ DInputKeyCodes::AXIS_X_ROT_NEG,   "X Rot -"        },
	{ DInputKeyCodes::AXIS_X_ROT_POS,   "X Rot +"        },
	{ DInputKeyCodes::AXIS_Y_ROT_NEG,   "Y Rot -"        },
	{ DInputKeyCodes::AXIS_Y_ROT_POS,   "Y Rot +"        },
	{ DInputKeyCodes::AXIS_Z_ROT_NEG,   "Z Rot -"        },
	{ DInputKeyCodes::AXIS_Z_ROT_POS,   "Z Rot +"        },
	{ DInputKeyCodes::SLIDER_1_NEG,     "Slider 1 -"     },
	{ DInputKeyCodes::SLIDER_1_POS,     "Slider 1 +"     },
	{ DInputKeyCodes::SLIDER_1_VEL_NEG, "Slider 1 Vel -" },
	{ DInputKeyCodes::SLIDER_1_VEL_NEG, "Slider 1 Vel +" },
	{ DInputKeyCodes::SLIDER_1_ACC_NEG, "Slider 1 Acc -" },
	{ DInputKeyCodes::SLIDER_1_ACC_NEG, "Slider 1 Acc +" },
	{ DInputKeyCodes::SLIDER_1_FOR_NEG, "Slider 1 For -" },
	{ DInputKeyCodes::SLIDER_1_FOR_NEG, "Slider 1 For +" },
	{ DInputKeyCodes::SLIDER_2_NEG,     "Slider 2 -"     },
	{ DInputKeyCodes::SLIDER_2_POS,     "Slider 2 +"     },
	{ DInputKeyCodes::SLIDER_2_VEL_NEG, "Slider 2 Vel -" },
	{ DInputKeyCodes::SLIDER_2_VEL_NEG, "Slider 2 Vel +" },
	{ DInputKeyCodes::SLIDER_2_ACC_NEG, "Slider 2 Acc -" },
	{ DInputKeyCodes::SLIDER_2_ACC_NEG, "Slider 2 Acc +" },
	{ DInputKeyCodes::SLIDER_2_FOR_NEG, "Slider 2 For -" },
	{ DInputKeyCodes::SLIDER_2_FOR_NEG, "Slider 2 For +" },
	{ DInputKeyCodes::BUTTON_1,         "BTN 1"          },
	{ DInputKeyCodes::BUTTON_2,         "BTN 2"          },
	{ DInputKeyCodes::BUTTON_3,         "BTN 3"          },
	{ DInputKeyCodes::BUTTON_4,         "BTN 4"          },
	{ DInputKeyCodes::BUTTON_5,         "BTN 5"          },
	{ DInputKeyCodes::BUTTON_6,         "BTN 6"          },
	{ DInputKeyCodes::BUTTON_7,         "BTN 7"          },
	{ DInputKeyCodes::BUTTON_8,         "BTN 8"          },
	{ DInputKeyCodes::BUTTON_9,         "BTN 9"          },
	{ DInputKeyCodes::BUTTON_10,        "BTN 10"         },
	{ DInputKeyCodes::BUTTON_11,        "BTN 11"         },
	{ DInputKeyCodes::BUTTON_12,        "BTN 12"         },
	{ DInputKeyCodes::BUTTON_13,        "BTN 13"         },
	{ DInputKeyCodes::BUTTON_14,        "BTN 14"         },
	{ DInputKeyCodes::BUTTON_15,        "BTN 15"         },
	{ DInputKeyCodes::BUTTON_16,        "BTN 16"         },
	{ DInputKeyCodes::BUTTON_17,        "BTN 17"         },
	{ DInputKeyCodes::BUTTON_18,        "BTN 18"         },
	{ DInputKeyCodes::BUTTON_19,        "BTN 19"         },
	{ DInputKeyCodes::BUTTON_20,        "BTN 20"         },
	{ DInputKeyCodes::BUTTON_21,        "BTN 21"         },
	{ DInputKeyCodes::BUTTON_22,        "BTN 22"         },
	{ DInputKeyCodes::BUTTON_23,        "BTN 23"         },
	{ DInputKeyCodes::BUTTON_24,        "BTN 24"         },
	{ DInputKeyCodes::BUTTON_25,        "BTN 25"         },
	{ DInputKeyCodes::BUTTON_26,        "BTN 26"         },
	{ DInputKeyCodes::BUTTON_27,        "BTN 27"         },
	{ DInputKeyCodes::BUTTON_28,        "BTN 28"         },
	{ DInputKeyCodes::BUTTON_29,        "BTN 29"         },
	{ DInputKeyCodes::BUTTON_30,        "BTN 30"         },
	{ DInputKeyCodes::BUTTON_31,        "BTN 31"         },
	{ DInputKeyCodes::BUTTON_32,        "BTN 32"         },
	{ DInputKeyCodes::BUTTON_33,        "BTN 33"         },
	{ DInputKeyCodes::BUTTON_34,        "BTN 34"         },
	{ DInputKeyCodes::BUTTON_35,        "BTN 35"         },
	{ DInputKeyCodes::BUTTON_36,        "BTN 36"         },
	{ DInputKeyCodes::BUTTON_37,        "BTN 37"         },
	{ DInputKeyCodes::BUTTON_38,        "BTN 38"         },
	{ DInputKeyCodes::BUTTON_39,        "BTN 39"         },
	{ DInputKeyCodes::BUTTON_40,        "BTN 40"         },
	{ DInputKeyCodes::BUTTON_41,        "BTN 41"         },
	{ DInputKeyCodes::BUTTON_42,        "BTN 42"         },
	{ DInputKeyCodes::BUTTON_43,        "BTN 43"         },
	{ DInputKeyCodes::BUTTON_44,        "BTN 44"         },
	{ DInputKeyCodes::BUTTON_45,        "BTN 45"         },
	{ DInputKeyCodes::BUTTON_46,        "BTN 46"         },
	{ DInputKeyCodes::BUTTON_47,        "BTN 47"         },
	{ DInputKeyCodes::BUTTON_48,        "BTN 48"         },
	{ DInputKeyCodes::BUTTON_49,        "BTN 49"         },
	{ DInputKeyCodes::BUTTON_50,        "BTN 50"         },
	{ DInputKeyCodes::BUTTON_51,        "BTN 51"         },
	{ DInputKeyCodes::BUTTON_52,        "BTN 52"         },
	{ DInputKeyCodes::BUTTON_53,        "BTN 53"         },
	{ DInputKeyCodes::BUTTON_54,        "BTN 54"         },
	{ DInputKeyCodes::BUTTON_55,        "BTN 55"         },
	{ DInputKeyCodes::BUTTON_56,        "BTN 56"         },
	{ DInputKeyCodes::BUTTON_57,        "BTN 57"         },
	{ DInputKeyCodes::BUTTON_58,        "BTN 58"         },
	{ DInputKeyCodes::BUTTON_59,        "BTN 59"         },
	{ DInputKeyCodes::BUTTON_60,        "BTN 60"         },
	{ DInputKeyCodes::BUTTON_61,        "BTN 61"         },
	{ DInputKeyCodes::BUTTON_62,        "BTN 62"         },
	{ DInputKeyCodes::BUTTON_63,        "BTN 63"         },
	{ DInputKeyCodes::BUTTON_64,        "BTN 64"         },
	{ DInputKeyCodes::BUTTON_65,        "BTN 65"         },
	{ DInputKeyCodes::BUTTON_66,        "BTN 66"         },
	{ DInputKeyCodes::BUTTON_67,        "BTN 67"         },
	{ DInputKeyCodes::BUTTON_68,        "BTN 68"         },
	{ DInputKeyCodes::BUTTON_69,        "BTN 69"         },
	{ DInputKeyCodes::BUTTON_70,        "BTN 70"         },
	{ DInputKeyCodes::BUTTON_71,        "BTN 71"         },
	{ DInputKeyCodes::BUTTON_72,        "BTN 72"         },
	{ DInputKeyCodes::BUTTON_73,        "BTN 73"         },
	{ DInputKeyCodes::BUTTON_74,        "BTN 74"         },
	{ DInputKeyCodes::BUTTON_75,        "BTN 75"         },
	{ DInputKeyCodes::BUTTON_76,        "BTN 76"         },
	{ DInputKeyCodes::BUTTON_77,        "BTN 77"         },
	{ DInputKeyCodes::BUTTON_78,        "BTN 78"         },
	{ DInputKeyCodes::BUTTON_79,        "BTN 79"         },
	{ DInputKeyCodes::BUTTON_80,        "BTN 80"         },
	{ DInputKeyCodes::BUTTON_81,        "BTN 81"         },
	{ DInputKeyCodes::BUTTON_82,        "BTN 82"         },
	{ DInputKeyCodes::BUTTON_83,        "BTN 83"         },
	{ DInputKeyCodes::BUTTON_84,        "BTN 84"         },
	{ DInputKeyCodes::BUTTON_85,        "BTN 85"         },
	{ DInputKeyCodes::BUTTON_86,        "BTN 86"         },
	{ DInputKeyCodes::BUTTON_87,        "BTN 87"         },
	{ DInputKeyCodes::BUTTON_88,        "BTN 88"         },
	{ DInputKeyCodes::BUTTON_89,        "BTN 89"         },
	{ DInputKeyCodes::BUTTON_90,        "BTN 90"         },
	{ DInputKeyCodes::BUTTON_91,        "BTN 91"         },
	{ DInputKeyCodes::BUTTON_92,        "BTN 92"         },
	{ DInputKeyCodes::BUTTON_93,        "BTN 93"         },
	{ DInputKeyCodes::BUTTON_94,        "BTN 94"         },
	{ DInputKeyCodes::BUTTON_95,        "BTN 95"         },
	{ DInputKeyCodes::BUTTON_96,        "BTN 96"         },
	{ DInputKeyCodes::BUTTON_97,        "BTN 97"         },
	{ DInputKeyCodes::BUTTON_98,        "BTN 98"         },
	{ DInputKeyCodes::BUTTON_99,        "BTN 99"         },
	{ DInputKeyCodes::BUTTON_100,       "BTN 100"        },
	{ DInputKeyCodes::BUTTON_101,       "BTN 101"        },
	{ DInputKeyCodes::BUTTON_102,       "BTN 102"        },
	{ DInputKeyCodes::BUTTON_103,       "BTN 103"        },
	{ DInputKeyCodes::BUTTON_104,       "BTN 104"        },
	{ DInputKeyCodes::BUTTON_105,       "BTN 105"        },
	{ DInputKeyCodes::BUTTON_106,       "BTN 106"        },
	{ DInputKeyCodes::BUTTON_107,       "BTN 107"        },
	{ DInputKeyCodes::BUTTON_108,       "BTN 108"        },
	{ DInputKeyCodes::BUTTON_109,       "BTN 109"        },
	{ DInputKeyCodes::BUTTON_110,       "BTN 110"        },
	{ DInputKeyCodes::BUTTON_111,       "BTN 111"        },
	{ DInputKeyCodes::BUTTON_112,       "BTN 112"        },
	{ DInputKeyCodes::BUTTON_113,       "BTN 113"        },
	{ DInputKeyCodes::BUTTON_114,       "BTN 114"        },
	{ DInputKeyCodes::BUTTON_115,       "BTN 115"        },
	{ DInputKeyCodes::BUTTON_116,       "BTN 116"        },
	{ DInputKeyCodes::BUTTON_117,       "BTN 117"        },
	{ DInputKeyCodes::BUTTON_118,       "BTN 118"        },
	{ DInputKeyCodes::BUTTON_119,       "BTN 119"        },
	{ DInputKeyCodes::BUTTON_120,       "BTN 120"        },
	{ DInputKeyCodes::BUTTON_121,       "BTN 121"        },
	{ DInputKeyCodes::BUTTON_122,       "BTN 122"        },
	{ DInputKeyCodes::BUTTON_123,       "BTN 123"        },
	{ DInputKeyCodes::BUTTON_124,       "BTN 124"        },
	{ DInputKeyCodes::BUTTON_125,       "BTN 125"        },
	{ DInputKeyCodes::BUTTON_126,       "BTN 126"        },
	{ DInputKeyCodes::BUTTON_127,       "BTN 127"        },
	{ DInputKeyCodes::BUTTON_128,       "BTN 128"        }
};
