name: Generate Translation Template

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'rpcs3/**'

jobs:
  Generate_Translation_Template:
    name: Generate Translation Template
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Install Qt Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y qt6-tools-dev qt6-l10n-tools

      - name: Generate .ts file using lupdate (Qt)
        run: |
          mkdir -p translations
          cd rpcs3  # Change to the rpcs3 directory
          LUPDATE_PATH=$(find /usr -name lupdate -type f 2>/dev/null | head -n 1)
          if [ -z "$LUPDATE_PATH" ]; then
            echo "Error: lupdate not found!"
            exit 1
          else
            echo "lupdate found at: $LUPDATE_PATH"
            $LUPDATE_PATH -recursive . -ts ../translations/rpcs3_template.ts
            sed -i 's|filename="\.\./|filename="./|g' ../translations/rpcs3_template.ts
          fi

      - name: Upload translation template
        uses: actions/upload-artifact@main
        with:
          name: RPCS3_Translation_Template
          path: translations/rpcs3_template.ts
          compression-level: 0
