# Runs steps to triage an incoming Pull Request, for example - applying labels.
name: Pull Request Triage

on: [pull_request_target]

jobs:
  label:
    if: github.repository == 'RPCS3/rpcs3'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"